apu52/Travel_Website

- README.md
Title : New community contributors banner
Issue No. : #39
Code Stack : -
Close #39 
NO
> New community contributors banner

- index.html
- styles.css
Title :
Add a go to top button
Issue No. : #29 
Code Stack : JavaScript,Html,Css
Close #29 
Video/Screenshots (mandatory)
Additional context (Mandatory )
I have enhance the website by adding go to top button with the help of Javascript,Html,Css
Are you contributing under any Open-source programme?
Yes, JWOC
> ADD:add go to top button

- index.html
Title :
Resize the destination card (Equally)
Issue No. :
#31
Code Stack : 
HTML
Close #31 
Standardize the size of image boxes within the Destination section for a uniform and balanced layout.
Adjust the dimensions of images or containers to ensure a symmetric presentation.
Yes,under Jwoc
> Bug:Standardize destination card(equally)

- index.html
- styles.css
Title : Feature_Request Add animation to 'Best Trip Package' Section 
Issue No. : #46
Code Stack : HTML , CSS
Close #46
https://github.com/apu52/Travel_Website/assets/149994109/a8ce3e83-f21a-46d3-a907-88068c694971
I have added animation to images in 'Best Trip Package' section and also made sizes of all images uniform for same.
Yes, I have completed this issue under JWOC.
> Animation for 'Best Trip Package' section image done

- styles.css
Title :
Enhancement of navbar.
Issue No. : #57 
Close #57 
I am contributing under JWoC 24
> navbar enhanced

- index.html
- styles.css
Title : Style of Button want to change
Button is inside the textfield so we want to apply border-radius
Issue No. : #58 
Code Stack : 
Close #58 
JWOC
> Fix#58 Style the send button

- styles.css
Title :Fix navigation bar and remove resizing  #84 
Issue No. : #84 
Code Stack : HTML,JS,CSS.
Close #84
before:
https://github.com/apu52/Travel_Website/assets/142984776/f8c4e468-7fff-4727-9263-e6f5c1314b84
After 
https://github.com/apu52/Travel_Website/assets/142984776/9b78c5d6-b6e7-400e-b6cc-08084a393546
Contributing under JWoC'24.
> [FIX] : Fixes navigation bar #84

- styles.css
Title : FIXED nav bar 
Issue No. : FIXES #81 
Close #81 
https://github.com/apu52/Travel_Website/assets/143163927/f246486b-00e4-4261-9d8f-0b7851096f84
JWOC,2024
> [FIX]: Nav bar

- styles.css
Title :[BUG ]: Alignment Problems
Issue No. : #70
Code Stack : CSS, HTML
Close #70 
YES, under JWOC 2024
> Fixing Alignment Problems

- Image-Gallery/style.css
- index.html
Title : Gallery page destination is fixed #73
Issue No. : #73 
Close #73 
[travel_guide.webm](https://github.com/apu52/Travel_Website/assets/83652986/a0c1f327-5c31-4462-9005-95d535780583)
> gallery-view

- styles.css
Title : Add custom scrollbar styling for the Website.
Issue No. : #91 
Close #91 
https://github.com/apu52/Travel_Website/assets/142984776/c7bb342f-67d8-4404-ad9d-4dfe3a9ee803
**Working under JWoC'24.**
>  FIX : #91 [Added custom scrollbar styling for the website]

- index.html
- styles.css
Issue No. : #99 
Close #99 
I have added footer classes: Connect With Us and Explore. 
JWOC'24
> addition of more footer classes

- index.html
- styles.css
Title : Documentation
Issue No. :#61
Code Stack : 
Close #61 
https://github.com/apu52/Travel_Website/assets/140962818/0f16d741-e746-4faa-bede-f0f666ec942b
A toggle button is add to switch between light to dark theme.
> Documentation

- index.html
Title : added typed text in hero section 
Issue No. : #104
Code Stack : javascript
Close #104 
https://github.com/apu52/Travel_Website/assets/110532770/b970b435-5370-4141-bf4f-f0e79f46cd2d
Jwoc'24
> added typed text in hero section

- feedback.html
- feedback.js
- style_.css
Title :Revamp the feedback page according to the existing theme of website
Issue No. :#108
Code Stack : 
Close #108 
Yes under JWOC 2024
>  Revamped the feedback page

- index.html
Title :Added Animations
Issue No. : #109
Code Stack :  HTML , CSS , JS
Close #109 
https://github.com/apu52/Travel_Website/assets/124901633/f0183b1d-2744-45bf-8753-67223ffdaaef
Yes , in JWOC 2024.
> Added Animations

- styles.css
Title : BUG : Alignment
Issue No. : #118 
Code Stack : HTML CSS
Close #118 
The alignment of the section-container and the gallary-container is fixed.
Thus, the bug is resolved.
Yes. I am contributing it under JWOC'24
> BUG : Alignment Fixed

- index.html
Title :Link logo to Homepage
Issue No. : #110 
Code Stack : 
HTML
Close #110
screenshot
Yes,under JWOC.
> Link logo to Homepage

- feedback.html
- feedback.js
- style_.css
Feature_Request #143
Title : Feature_Request 
Issue No.  #143
Code Stack : HTML,CSS,JS
Close #143
I have added the feedback section.
JWOC
> feedback box added.

- styles.css
feat:updated style.css
Title :Enhanced responsivness
Issue No. : https://github.com/apu52/Travel_Website/issues/137
[Screencast from 22-01-24 11:40:25 PM IST.webm](https://github.com/apu52/Travel_Website/assets/127125259/0fb1e810-1e1a-4101-856e-a7934ca22b7f)
Close : #137
> feat:updated style.css

- Image-Gallery/style.css
- index.html
- styles.css
Title : Feature_Request Define the one proper color to navbar and footer #74
Issue No. : #74 
Code Stack : 
HTML, CSS 
Close #74 
JWOC
> Fix#74 style header footer color 

- index.html
Title : embedded map
Issue No. : #154 
Code Stack : Html CSS Google map embeddings
Close #154
jwoc'24
> embedded map

- index.html
- plantrip.html
Title :Added Plan Trip page
Issue No. :#134
Code Stack : HTML CSS
Close #134 
Yes , I am contributing under JWoC 24
> Plantrip page added

- index.html
- pricing/index.html
- pricing/style.css
Title :Feature_Request: Add membership pricing table 
Issue No. : 162
Close #162 
Please check and close issue.
> Feature_Request: Add membership pricing table #162

- story.html
- styles.css
Title : New Video #151 
Issue No. : 151
Code Stack : HTML ,CSS
Close #151 
https://github.com/apu52/Travel_Website/assets/146833908/e18f9cc7-0e79-406d-8eca-9a9a3629ad8e
1. Change the name of new video for proper working .
2. Updated the story.html.
3. Updated CSS in styles.css to fix the video button on index.html and also correctly display the video.
Contributing under JWOC
> BUG : New video Fixed (#151)

- faq.html
- feedback.html
- login.html
- payment.html
- plantrip.html
Title :Link favicon icon to other pages.
Issue No. :#171
Code Stack : 
Close #171 
#171
JWOC
Please review my pull request
> Added favicon icon to the pages

- styles.css
Title : fixed go to top button
Issue No. : #163 
Close #163
jwoc'24
> fixed go to top button

- index.html
Title : overflow fixed
Issue No. : #181
Code Stack : html
Close #181 
JWOC'24
> overflow fixed

- index.html
- index.js
- styles.css
Title : Add Newsletter Modal 
- Issue No. : #175 
- Close #175
I'm Contributing under JWOC.
> [ISSUE - 175] Add newsletter pop up box

- index.html
- privacy.html
- tnc.html
Title : privacy policy page
Issue No. : #193 
Code Stack : html css bootstrap
Close #193 
linked privacy policy button in footer with this page
jwoc'24
> privacy policy page

- index.html
- styles.css
Title : Made the Website Responsive in Desktop Version.
Issue No. : **#178** 
Code Stack : HTML , CSS , JS
Close #178 
https://github.com/apu52/Travel_Website/assets/124901633/b90acd27-cad3-4721-93bf-770418acb73d
Have made the website responsive and changed the background animation !
Yes , under JWOC 2024.
> Made the Website Responsive in Desktop Version.

- feedback.html
- feedback.js
- index.html
- style_.css
Title : Enhanced feedback page and changed reviews to gallery in the navbar.
Issue No. :#184
Code Stack : HTML ,CSS ,JS
Close #184 
Yes, I am contributing under JWoC 24
> Enhanced feedback page

- index.html
Title : fixed offtheme button
Issue No. : #215 
Code Stack : html csss bootstrap
Close #215
JWOC'24
> fixed offtheme button

- index.html
- styles.css
Title : Updated Contact form
Issue No. : #211
Close #211 
Yes, I am working under JWOC 2024.
> Updated Contact Form

- Theme.js
- index.html
- styles.css
Title :Enhancing the dark mode toggle button
Issue No. :#218
Code Stack : 
Close #218 
https://github.com/apu52/Travel_Website/assets/140010647/d72aa80f-bdcb-4c8b-82cb-8e23302dc779
Yes under JWOC'24
> Added icons in dark mode button

- index.html
- index.js
- styles.css
Title :  BUG validation for Subscribe button #226
Issue No. : #226 
Code Stack : 
Close #226 
jwoc
> fixed#226 added validation  to subscribe textfield  

- index.html
Title :BUG : CHATBOT
Issue No. : #174 
Code Stack :  html ,css, js
Close : #174 
jwoc
> Make the chatbot functional  and added more responses

- index.html
- styles.css
Title : dark mode update
Issue No. : #207 
Code Stack :  
Close #207 
https://github.com/apu52/Travel_Website/assets/125949765/6f73b4f4-411c-4e8d-83dd-bde3513691f2
jwoc
> Darkmode improved 

- styles.css
Title :  Navbar hiding the content #230
Issue No. : #230 
Code Stack : 
Close #230 
jwoc
>  fixed Navbar hiding the content #230

- payment.html
- pricing/index.html
Title : Membership page linked to checkout page
Issue No. : #220
Close : #220
jwoc'24
> Membership page linked to checkout page

- index.html
- newLogin.css
- newLogin.html
Title : Improve UI of the Login Page
Issue No. : #223
Code Stack : HTML , CSS , JS
Close #223 
https://github.com/apu52/Travel_Website/assets/124901633/6eb7bd5e-089a-497d-922d-2064a652a2ea
Redesigned the Login Page by providing a Glassmorphic Design ! Added animations too to make it more impressive !!
YES , UNDER JWOC 2024.
> Improve UI of the Login Page

- index.html
Title : fixed unusual button
Issue No. : #238
Close #238
JWoC'24
> fixed unusual button

- styles.css
Title : fixed alignment of go to top button
Issue No. : #244
Close #244
jwoc'24
> fixed alignment of go to top button

- Image-Gallery/style.css
- Theme.js
- index.html
- styles.css
Title : fix #234  navbar item arrangement in proper way 
Issue No. : #234 
Code Stack :  
Close #234 
https://github.com/apu52/Travel_Website/assets/125949765/12592257-c1b5-4500-bccb-2ce577d30b57
jwoc
> fix #243 navbar item arrangement in proper way 

- dedicated destinations/Santorini ,Aegean Sea/start.html
Title : fixed santorini page
Issue No. : #247 
Close #247 
jwoc'24
> fixed santorini page

- Image-Gallery/style.css
- index.html
- styles.css
Title  : New btn style for both mode #235
Issue No. : #235 
Code Stack : 
Close #235 
https://github.com/apu52/Travel_Website/assets/125949765/d7ac7e01-4c29-4291-983f-bdd81d3bd06d
JWOC
Bro it is not that much easy 
pls change label to hard
> New btn style for both mode #235

- dedicated destinations/Santorini ,Aegean Sea/start.html
- dedicated destinations/Santorini ,Aegean Sea/tour.css
- index.html
@apu52 PLEASE MERGE THIS AT FIRST, IF IT WORKS FINE THEN WILL JUST EDIT THE REST OF THE STUFF AND PUT A FINAL PULL REQUEST!
#JWOC 2024
> TEST MERGE!!

- payment.html
Title : fix links in payment page
Issue No. : #252 
Close #252
https://github.com/apu52/Travel_Website/assets/110532770/62ba9ac4-4a43-4585-ac16-723ecf1ed23f
jwoc'24
> fix links in payment page

- Image-Gallery/style.css
- index.html
Title : Invisible Text in Footer on Dark Mode Switch #253
Issue No. :  #253
Close #253
The reported issue of invisible text in the footer during the transition from light mode to dark mode has been successfully resolved.
> Invisible Text in Footer on Dark Mode Switch #253

- index.html
Title : add padding between button
Issue No. : #255 
Close #255 
jwoc'24
> add padding

- dedicated destinations/Dubai/Dubai.css
- dedicated destinations/Dubai/start.html
- dedicated destinations/Goa/Goa.css
- dedicated destinations/Goa/start.html
- dedicated destinations/Grand Canyon National Park ,Arizona/Grand_start.html
- dedicated destinations/Grand Canyon National Park ,Arizona/Grand_tour.css
- dedicated destinations/London/London.css
- dedicated destinations/London/start.html
- dedicated destinations/Machu Picchu ,Peru/Machu_start.html
- dedicated destinations/Machu Picchu ,Peru/Machu_tour.css
- dedicated destinations/NewYork/NewYork.css
- dedicated destinations/NewYork/start.html
- dedicated destinations/Paris/Paris.css
- dedicated destinations/Paris/start.html
THE STYLES SHEEET IS UNLINKED AND
AND DEDICATED STYLES ARE ADDED .
THE DARK/LIGHT MODE BUTTON IS REMOVED FROM THE HEADER OF THIS PAGES!
Title : [Feature_Request] COMPLETE NEW HEADER AND FOOTER FOR THE DESTINATIONS
Issue No. : #212  JWOC 2024
Code Stack : HTML CSS AND JS
Close #212 
JWOC 2024
> ALL PAGES ARE FIXED

- index.html
- styles.css
Title : Feature_Request new sub title style for both mode #236
Issue No. : #236 
Code Stack : 
Close #236 
jwoc
> new sub title style for both mode #236

- styles.css
Title: Invisible text in the pricing section on switching to dark mode #259
Issue No. : #259
Close #259
**Additional context **
Resolved the issue of text disappearing in pricing(trip-details) section while switching to dark mode
JWOC 2024
> Invisible text in the pricing section on switching to dark mode #259

- package.html
Title : fix go to top on packages page
Issue No. : #260 
Close #260 
jwoc'24
> fix go to top on packages page

- payment.html
- payment.js
Title : Enhancement and Bug Fixes for Payment Gateway
Issue No. : #267
Code Stack : Frontend
Validation Added in the Billing Address content. Balance Form Validations are coming out the way.
> Validation applied on Billing Address Content in Payment page

- index.html
- styles.css
Title : Add a Custom Scrollbar 
Issue No. : #273 
Code Stack :  HTML , CSS , JS
Close #273 
Yes , under JWOC 2024.
> Add a Custom Scrollbar 

- story.html
Title : BUG Navbar mismatch to story page #262
Issue No. : #262 
Code Stack : 
Close : #262
JWOC
> BUG Navbar mismatch to story page #262

- feedback.js
Title :  Improvement in Rate Us Page
Issue No. : #277 
Code Stack :  HTML , CSS , JS
Close #277 
https://github.com/apu52/Travel_Website/assets/124901633/5924aad2-eb69-4fb6-8de6-0b064346eae1
Yes , under JWOC 2024.
> Improvement in Rate Us Page

- index.html
- styles.css
Title : Feature_Request remove bubble background #280
Issue No. : #280 
Code Stack : 
Close #280 
https://github.com/apu52/Travel_Website/assets/125949765/5542e657-5700-463a-b0f6-7231da864007
JWOC
> Feature_Request remove bubble background #280

- index.html
- styles.css
Title : BUG Improper style for about us section #285
Issue No. : #285 
Code Stack : 
Close #285 
JWOC
> BUG Improper style for about us section #285

- dedicated destinations/Dubai/main.js
- dedicated destinations/Dubai/start.html
- dedicated destinations/Goa/main.js
- dedicated destinations/Goa/start.html
- dedicated destinations/Grand Canyon National Park ,Arizona/Grand_main.js
- dedicated destinations/Grand Canyon National Park ,Arizona/Grand_start.html
- dedicated destinations/London/main.js
- dedicated destinations/London/start.html
- dedicated destinations/Machu Picchu ,Peru/Machu_main.js
- dedicated destinations/Machu Picchu ,Peru/Machu_start.html
- dedicated destinations/Maldives/main.js
- dedicated destinations/Maldives/start.html
- dedicated destinations/NewYork/main.js
- dedicated destinations/NewYork/start.html
- dedicated destinations/Paris/main.js
- dedicated destinations/Paris/start.html
- dedicated destinations/Santorini ,Aegean Sea/main.js
- dedicated destinations/Santorini ,Aegean Sea/start.html
- dedicated destinations/bali/main.js
- dedicated destinations/bali/start.html
- dedicated destinations/brazil/main.js
- dedicated destinations/brazil/start.html
- dedicated destinations/kashmir/main.js
- dedicated destinations/kashmir/start.html
Title : Climate Info Added.
Issue No. : #270 
Code Stack :  html, js, css
Close #270 
Sorry for the delay! I have used free rapidAPI and added the climate info(marked In blue) In evey Single page.
JWOC.
> climate info

- package.html
Title : Add Animations to the Pricing Page !
Issue No. : #289 
Code Stack : HTML, CSS , JS
Close #289 
https://github.com/apu52/Travel_Website/assets/124901633/c9c42391-1689-4d76-bebb-6d59da41b374
Yes , in JWOC 2024.
> Add Animations to the Pricing Page !

- index.html
- styles.css
Title :Text visiblity in contact us page.
Issue No. : #292  
Code Stack : css
Close #292 
**Working under JWOC**
> FIX: Text visibility in light mode

- styles.css
Title :  BUG Style mismatch to testimonial section #290
Issue No. :  #290 
Code Stack :  #290 
Close #290 
JWOC
> BUG Style mismatch to testimonial section #290

- feedback.html
- style_.css
BUG[Improving UI of Rate US PAGE] #298
Title :BUG[Improving UI of Rate US PAGE]
Issue No. : #298 
Close #298 
Yes, JWOC'24 phase 2
> BUG[Improving UI of Rate US PAGE] #298

- styles.css
Title :  BUG Testimonials section is hide the bubble #294
Issue No. :  #294 
Code Stack : 
Close #294 
JWOC
> BUG Testimonials section is hide the bubble #294

- styles.css
Title : card hover effect
Issue No. : #335
Close #335
GSSOC'24
> Improved the hover effect 

- index.html
Title : Fixed routing issue
Issue No. : #364
Code Stack : navigation html css
Close #364
No more new tabs when redirecting to new pages
Checklist:
[X] I have mentioned the issue number in my Pull Request.
[X] I have commented my code, particularly in hard-to-understand areas
[X] I have gone through the contributing.md file before contributing
Additional context (Mandatory )
Are you contributing under any Open-source program?
yes i am contributing under GSSOC24 open source program
> fixed routing bug

- index.html
I Have solved the copyright bug using javascript, now it will display current year. Thankyou
Title :  BUG in copyright
Issue No. : #337 
Code Stack : Html, Javascript
Close #337 >
Attached
I love to contribute in this project. Thankyou
Yes, Under Gssoc24.
> solved the copyrightBUG_index.html

- styles.css
Title : Inonsistency in fonts of headings #372
Issue No. : #372
Code Stack : 
Close #372 
GSSoC'24
> Inonsistency in fonts of headings

- .github/workflows/greetings.yaml
Title : Enable Github Actions for Greeting
Issue No. : #324 
Code Stack : Github Actions
Close #324 
N/A
`GSSOC 2024`
> Greetings added 

- payment.css
- payment.html
@apu52 
Title : fixing breadcrumb style
Issue No. :
#402
Code Stack : 
Close #402
> fixing style of breadcrumb

- index.js
- styles.css
Title :Feature enhancement: visibility of text in dark mode and auto sliding of images in top destinations
Issue No. : #410 
Code Stack : 
Close #410 
Before:
After:
before:
https://github.com/apu52/Travel_Website/assets/152693538/a659d892-41a4-4ab4-ab04-9cb1210cf991
after:
https://github.com/apu52/Travel_Website/assets/152693538/332c4451-1d1c-455e-b0bc-ad01442b43da
for reference you can check this:
https://neerajagurram.github.io/Travel_Website/
- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have gone through the  `contributing.md` file before contributing
changes made:
- visibility of "watch our story" in dark theme ✔
- auto sliding of images near top …
> Feature enhancement: visibility of text in dark mode and auto sliding of images in top destinations

- feedback.html
- login.html
- newLogin.css
- newLogin.html
- style_.css
- styles.css
Title :  BUG: Navbar Links are not aligned properly
Issue No. : 387
Code Stack :  
Fixed the navlinks on the desktop orientation
Added navbar to login and rate us page 
Close #387 
GSSOC'24
> Navbar changes

- feed.css
- feed.html
- feed.js
I have added the styles to the feedback form.
Title : Feedback Form Styles added.
Issue No. : #463 
Close #463 
I am contributing under GSSoC'24.
> #463 Added Styles to Feedback form

- .vscode/launch.json
- index.js
Title : Feature request
Issue No. : #458 
Code Stack : 
// Close the modal when clicking outside the modal content (new code)
window.addEventListener("click", (e) => {
if (e.target === modalContainer) {
closeModal();
}
});
// Close the modal when clicking the exit button (new code)
closeBtn.addEventListener("click", closeModal);
Close #458 
I have added js code so that the modal window can be closed clicking outsidw the window 
Yes I am GSSoC '24 contributor 
https://github.com/apu52/Travel_Website/assets/121795329/90f85eed-8e7c-48e6-b494-ef5068847593
> I have fixed the modal window

- styles.css
Title :The contact us page is not responsive.
Issue No. :#406
Close #406
Yes I am contributing under GGSOC'24
> Responsive contact us

- plantrip.html
Title : End Date Can Be Set Earlier Than Start Date
Issue No. :#523
Close #523
Date Validation: Added JavaScript validation to ensure the end date cannot be earlier than the start date.
Alert Message: Displays an alert if the end date is earlier than the start date, preventing form submission.
GSSOC'24
> fixed date issue

- explore.css
- explore.js
- index.html
Title : Modifying Explore Destination section
Issue No. : 326
Code Stack : HTML,CSS,JS
Close #326 
https://github.com/apu52/Travel_Website/assets/126314871/7ab47b00-4419-4095-aa95-1c6f315f7c76
Yes, I am contributing under GSSoC'24.
> modifying explore destination section

- index.html
Title : Beautify the UI Page
Issue No. :#366
Code Stack : HTML CSS
Close #366
#366
GSSoC
> Beautify the UI Page

- index.html
Title :About the newsletter section
Issue No. : #483 
Code Stack : html
Close #483 
This is another PR for the issue #483 as the earlier one had merge conflicts. Changes are same. Sorry for the inconvenience.
Yes , GSSOC'24.
> Fixed issue #483

- styles.css
Title : Creating Curved Corners for the Video 
Issue No. : #501
Code Stack :  
Created Curved Corners for the Video
Close #501
Curved corners have been added to the video for a sleek and modern appearance. This design choice enhances visual appeal and gives the video a softer, more refined look. The rounded edges create a smooth and elegant frame around the content.
> Created Curved Corners for the Video 

- styles.css
Feature_Request Testimonial needs to be responsive #507
Title : Feature_Request Testimonial needs to be responsive 
Issue No. : #507
Code Stack : 
Close #507
issue number #507
Gssoc 24
> Feature_Request Testimonial needs to be responsive #507

- pricing/style.css
- styles.css
After click on membership in mobile view it is not showing all and also not scrollable #509
Title : After click on membership in mobile view it is not showing all and also not scrollable 
Issue No. : #509 
Code Stack : 
Close #509
https://github.com/apu52/Travel_Website/assets/59639410/44511e12-626c-4cfe-9ff3-f544a9b08431
Gssoc 24
> Enhancement gssoc=issue509

- index.html
- index.js
- login.html
- newLogin.html
Title : BUG: Website auto refreshing after submitting contact us.
Issue No. : #492
Code Stack : html, javaScript
Close #492 
https://github.com/apu52/Travel_Website/assets/134281589/36a8475a-6029-440b-8b61-93181c381265
I have made few changes in index.html, index.js, newLogin.html, login.html. I fixed the issue with contact us form and It is working correctly now. I have used emailJs library and email will be sent to website mail(i.e tour@tourguide.com). I have also added email patterns in few input areas which provide more security.
Thank you for assigning me with this issue.
GSSOC 2024
> Resolved issues regarding contact us form.

- index.html
Title : Chatbot restart button is not working properly
Issue No. : #351 
Code Stack : 
Close #351
https://github.com/apu52/Travel_Website/assets/109607812/9a8e5ef4-9817-46aa-ab37-54a92d35297b
GSSoc
> Updated chatbot

- plantrip.html
Title : Added home button on Plan trip page
Issue No. : #489 
Code Stack : HTML , CSS
Close #489 
GSSOC'24
> Added home button on Plan trip page

- styles.css
the UX of TOP DESTINATION PAGE has
improved.
Title :To improve the UX of the TOP DESTINATION Page 
Issue No. : #599 
Close #599 
yes i am contributing under gssoc 24
> #599 solved

- index.html
- mouseEffect.css
- mouseEffect.js
Title :
Issue No. : #526 
Close #526
Code Stack:
- Add the JavaScript file named mouseEffect.js
- Add the CSS file named mouseEffect.css
https://github.com/apu52/Travel_Website/assets/134833235/f0524254-2fcc-4f24-9221-d34a2b75517f
> add mouse effect js and css

- index.html
- styles.css
Title: Scrollbar Missing
Issue No. :#350
Bug: The scroll bar is not working properly (can't go up once scrolled down).
Fixed: Added scrollup btn. refer video.
Close https://github.com/apu52/Travel_Website/issues/350
https://github.com/apu52/Travel_Website/assets/109607812/610bf871-baab-4865-bc39-26e98c4ed18c
GSSoC
> Scroll bar issue

- index.html
- styles.css
Title : Scrollbar Missing
Issue No. :#350
Bug: scroll bar is not working properly (Cant go up once scrolled down).
Fixed: Added scrollup btn. refer video.
Close #350 
https://github.com/apu52/Travel_Website/assets/109607812/bc41e08a-2f02-4d88-a9ce-8bc5b904a19a
GSSoc'24
> added scroll up button

- newLogin.css
Added cursor in "Login" button.
Title : Added cursor in "Login" button
Issue No. :  #547
Code Stack : 
Close #547
Before👆
After👇
> #547 Added cursor in "Login" button

- dedicated-destinations/bali/bali.css
Title : after click on book now on start.html page checkout need to be aligned 
Issue No. : #508 
Code Stack : 
Close #508
https://github.com/apu52/Travel_Website/assets/59639410/61c1bff5-f23f-4209-845b-1831db7a8850
Gssoc 24
> after click on book now on start.html page checkout need to be aligned 

- feedback.html
- index.html
- login-modified.html
- newplantrip.html
- package.html
- story.html
Title :Designing of login page and navigation of login button
Issue No. : #536 
Code Stack : 
1. HTML
2. CSS
3. JS
Close #536 
https://github.com/apu52/Travel_Website/assets/143430142/9e41e957-3f52-4069-9407-fbb0079b6488
The functionality of login button is modified in each and every page, Created separate pages for "register" and "login" separately and made the necessary navigations.
YES,I am contributing Under GSSOC
> login button is activated in every page

- feedback.html
- style_.css
Title : Rate us page UI improved
Issue No. : https://github.com/apu52/Travel_Website/issues/319
Issue title : Improve the UI of the RATE US Page
∙made changes to make the page consistent with the rest of the website
∙changed the fonts and buttons for consistency
∙changed the background image to match the theme and color palette
∙gave it an appealing and simplistic look and feel.
Code Stack :
Close #319 
- [ x] I have mentioned the issue number in my Pull Request.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have gone through the  `contributing.md` file before contributing
GSSOC'24
> rate us page UI improved

- newLogin.html
Changes made in the grammatical part of the page
Title: #502
Issue No. :#502
Code Stack : Html File
Close #502 
I have made changes in the newLogin.html file.
I am contributing in GSSOC 2024
> newLogin.html is corrected.

- payment.html
- payment.js
Title : Adding Strandard and Express Delivary options in the Payment #613
Issue No. :  #613 
Code Stack :  HTML, JavaScript
Close #613 
Added functionality to select a shipping method during checkout. Users can choose between standard and express shipping options, with the shipping cost dynamically updating based on the selection.
Standard Delivery
Express Delivery
I added JavaScript code to enable users to select between standard and express shipping methods during checkout. The shipping cost dynamically updates based on the selection. The total amount in the cart reflects the shipping cost addition.
I am a part of GSSoC 2024
> Added Strandard and Express Delivary options in the Payment 

- index.html
Title : Grammatical errors in the "Best trip package" section of the website
Issue No. : #640 
Code Stack : HTML and CSS
Close #640 
Corrected the grammatical error in the main page. Also, placed the commas at the correct positions. 
Before: 
After:
GSSOC'24
> Fixed grammar errors

- dedicated-destinations/Dubai/start.html
- dedicated-destinations/Goa/start.html
- dedicated-destinations/London/start.html
- dedicated-destinations/Maldives/start.html
- dedicated-destinations/Paris/start.html
- dedicated-destinations/bali/start.html
- dedicated-destinations/brazil/start.html
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_start.html
- dedicated-destinations/kashmir/start.html
- dedicated-destinations/machu-picchu-peru/Machu_start.html
- dedicated-destinations/new-york/start.html
- dedicated-destinations/santorini-aegean-sea/start.html
- index.html
- package.html
- story.html
- styles.css
Issue No. : #664 
Code Stack : 
Close #664
I have make the footer links active and also styled them properly
https://github.com/apu52/Travel_Website/assets/126975547/eb362761-9a9d-49a4-9a40-3a5acfea2e84
GSSoC'24
> Updated all the footer links in all the pages

- index.html
Title Navbar is not responsive.
Issue No. :#608
Close #608
I have made the navbar responsive by making changes in HTML,CSS files and adding media queries.
There was another bug which I have removed was that there were two login buttons on the navbar.
Yes under GSSOC'24
> Updated navbar for responsive view.

- styles.css
Title : Scroll top button
Issue No. : #576 
Code Stack : 
Close #576
On hover:
GSSoC
> Button enhanced.

- index.html
In contact us section after the user submits the form successfully, they see an alert box with the message "Email sent successfully! but the form was not reset. I have enhance the code so that the form will be reset, providing a better user experience.
Title : Enhancing the Contact Page
Issue No. :  #690
Close #690
Are you contributing under any Open-source programme?
GSSoC'24 (Girlscript Summer of Code)
> Update index.html #1002

- dedicated-destinations/London/start.html
- dedicated-destinations/Paris/start.html
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_start.html
- dedicated-destinations/machu-picchu-peru/Machu_start.html
- dedicated-destinations/new-york/start.html
- dedicated-destinations/santorini-aegean-sea/start.html
- package-lock.json
Title : [BUG] : Page not Responsing
Issue No. : #622
Close #622 
- `payment.html` page not responding `Bug` .It will be fixed.
[Screencast from 2024-05-26 16-44-58.webm](https://github.com/apu52/Travel_Website/assets/121082414/299e066a-bb9a-4257-afeb-a08b352421d6)
[Screencast from 2024-06-03 19-35-51.webm](https://github.com/apu52/Travel_Website/assets/121082414/4ed32573-53c1-4c0b-8d63-252b33e2dfce)
> [BUG] : Page not Responsing

- payment.html
Tittle: Navbar Updates in checkout page
Issue No. :#527
Code Stack : HTML ,CSS
Close #527 
This pull request adds a responsive navbar to the checkout page. The navbar includes links to the home page. This enhancement improves the navigation experience for users, allowing them to easily go back to home page of the website.
Added navbar component to the checkout page.
Updated CSS for the navbar to ensure it is responsive.
gssoc'24
> feat: Navbar updates in checkout

- index.html
- styles.css
Title : BUG: Footer of the website
Issue No. : #676
Code Stack : html &css
Close #676 
This is the new PR for issue  #676 as previous one had some conflicts . The changes are same.
Before: 
After : 
This is the new PR .
Yes, GSSOC'24.
> fix: Footer Changes (issue #676)

- index.html
- styles.css
Title : Contact page enhanced.
Issue No. : #579 
Code Stack : 
Close #579
I have enhanced contact page by adding icons and box shadow to look more attractive.
Please add gssoc and level label.
I am contributing under GSSOC'24.
> feat: contact page enhanced

- index.html
- mapa.html
- maps.css
- maps.js
task complete
Title and Issue number
Title : introduce google maps
Issue No. :https://github.com/apu52/Travel_Website/issues/572
Code Stack :
Close https://github.com/apu52/Travel_Website/issues/572
Description
Video/Screenshots (mandatory)
we @Shivani756 and @litesh1123 have completed the task
Type of PR
Bug fix
Documentation update
Other (specify): _______________
Checklist:
Additional context:
i have introduced the feature of google maps allowing the user to locate places with ease.
i have used javascript api for this purpose on the google cloud platform
i am countributing in gssoc 24 only
> feat: Introducing Google maps

- index.html
Title : Adding logo beside title in navbar
Issue No. : #573
Code Stack : 
Close #573
I have added logo beside title in navbar
Please add GSSOC and level label.
I am Contributing under GSSOC'24
> feat: logo added beside title in navbar

- affordable-destinations.html
Issue No. : #774 
Code Stack : 
1. html
2. css
Close #774 
YES,under gssoc
> fix: Image and css added

- 404.html
Title :Addition of 404 page
Issue No. : #609
Close #609
Added a animation and a home button
https://github.com/apu52/Travel_Website/assets/119691733/ac28f9de-6478-44df-bc66-b3b5f7974d41
GSSoC'24
> feat: added error 404 page

- Image-Gallery/script.js
#878 
Title : Title: Add Keyboard Navigation to Image Gallery
Issue No. : #878 
Code Stack : 
Close #878 
This feature enables users to navigate through the image gallery using the left and right arrow keys on their keyboard, providing a more seamless and accessible browsing experience.
https://youtu.be/2vQ71PpDSq8
- ✅ Feature enhancement
- ✅ I have performed a self-review of my code.
- ✅ I have commented my code, particularly in hard-to-understand areas.
- ✅ I have tested the changes thoroughly before submitting this pull request.
- ✅ I have provided relevant issue numbers, screenshots, and videos after making the changes.
- ✅ I have gone through the  `contributing.md` file before contributing
This enhancement aims to improve user experience and accessibility by allowing users to …
> feat: Added keyboard navigation to image gallery

- login/login.css
- login/script.js
- newLogin.html
Title :
Issue No. : #764 
Code Stack : 
html
css
javaScript
Close #764
The login button was not functional. Now it successfully redirects to  the homepage
https://github.com/apu52/Travel_Website/assets/142666229/579d542c-1bac-470b-9a9d-eeb43065f5bb
GSSoC'24
GSSoC'24
> feat: added functionality to login page

- index.html
- styles.css
Title :  Remove the bubbles animation from the landing page
Issue No. : #928
Close #928 
Remove the bubbles animation from the landing page
> fix: Issue #928 Remove Bubble From Landing page

- index.html
- styles.css
Title :Navbar is not responsive
Issue No. : #922
Close #922
I have made a completely responsive navbar which is now properly visible in all kind of devices.
Yes
> fix: Updated the navbar for responsive view.

- index.html
- styles.css
Title : BUG : Text Alignment in Page headings and Description
Issue No. : #801 
Code Stack : 
Close #801 
Text alignment of the home page is done giving a proper look .
Issue resolved review -
Please review @apu52. Suggest any changes if needed. 
> fix: Text alignment of home page

- feedback.html
- package.html
Title :  'Contact Us' Link Issues in Footer and Header section! 
Issue No. : #850 
Close #850
I have added following things:
The "Contact Us" link in the footer section of Package page is now navigating to the appropriate section on the home Page.
The "Contact Us" link in the header and footer on the feedback page is now navigating to the correct section on the home page.
Additionally, the phone number and email address in the footer of Package page are now clickable links that open the default email client and calling app, respectively.
GSSoC'24
> fix: Fixed the issue of Contact Us links in footer and header section

- index.html
Title : Pops up message on successful subscription in the main page.
Issue No. :#891
Code Stack : HTML | JS
Close #891 
Subscription successful message added when email id is entered.
The success message gets displayed on successful subscription.
> fix: Pops up message on successful subscription #891

- index.html
- tilt.css
- tilt.js
Title :Addition of Increasing Number Effect.
Issue No. : #724
Code Stack : html,css,js
Close #724 
Added Increasing number effect on the following part of website to make it more appealing.
https://github.com/apu52/Travel_Website/assets/159264060/a94792fa-b1b4-4c6e-8f8f-f4f085de40c3
GSSOC
> feat: Added Increasing number effect

- feed.css
- feed.html
- feed.js
Title : UI improvement for feedback form to match website theme
Issue No. : #751
Close #751
Improved the UI of feedback form
Added pop-up display when the form is submitted and if the incomplete information is filled.
Added social media icons , so that they could follow us and contact us before the feedback.
Before :
After:
https://github.com/apu52/Travel_Website/assets/168854094/07f0627d-f9b2-477e-a584-a15736b50ad4
Also made it responsive:
https://github.com/apu52/Travel_Website/assets/168854094/16d66c56-066d-41f2-aae5-062d437751ab
Feature enhancement
GSSoC'24
-  I am contributing under `GSSOC'24`
> feat: UI for feedback form to match website theme

- Blog/dumont.css
- Blog/dumont.html
- Blog/dumont.js
- Blog/kashmir.css
- Blog/kashmir.html
- Blog/kashmir.js
- Blog/kepler.css
- Blog/kepler.html
- Blog/kepler.js
- Blog/kesugi.css
- Blog/kesugi.html
- Blog/kesugi.js
- Blog/varanasi.css
- Blog/varanasi.html
- Blog/varanasi.js
- index.html
- trending.css
- trending.html
Title : Trending page made which connects to 5 more blogpages made by me with carefully aggregating pictures that makes them more attractive.
Issue No. : #915 
Code Stack : 
Close #915 
https://github.com/apu52/Travel_Website/assets/143064148/8b76fcac-ddec-4295-bd25-4166819bb291
> fix:  Issue #915 TRENDING SECTION WITH BLOGS ADDED

- index.html
- styles.css
Title : feat : Improvement of UI for Footer
Issue No. : #904
Code Stack : HTML and CSS
Close #904
Added hover effect and border to the headings.
Changed color of sub headings.
Added hover effect on the clickable subheading.
Improved Layout of- Places You May Want to Visit, Social Media, Address, Reach Out To Us, Follow Us
https://github.com/apu52/Travel_Website/assets/134837879/b62ea38f-dd28-481d-8d65-8f3f6b69d606
##Are you contributing under any Open-source program?
> feat: Improvement of UI for Footer 

- index.html
- styles.css
Title : feat : Improvement of UI for Footer
Issue No. : #904
Code Stack : HTML and CSS
Close #904
Added hover effect and border to the headings.
Changed color of sub headings.
Added hover effect on the clickable subheading.
Improved Layout of- Places You May Want to Visit, Social Media, Address, Reach Out To Us, Follow Us
https://github.com/apu52/Travel_Website/assets/134837879/884efe1a-1e6b-4455-94df-28ab9abf0e29
##Are you contributing under any Open-source program?
>  feat: Improvement of UI for Footer

- .vscode/settings.json
- login/login.css
- login/script.js
- newLogin.html
Title : [Feat]:- Password Hide and Show button
Issue No. : #715
Code Stack :
#715
Added a show and hide button in the password input for user-friendly
https://github.com/apu52/Travel_Website/assets/121508628/896e5586-c5c9-4dcd-b4cb-e2d8df7f2bc1
**If it's not good, please assign me again I will do it better**
> feat: Password Hide and Show button

- feedback.html
- styles.css
Title :On click of the hamburger icon in the Rate Us page nothing happens.
Issue No. : #923
Code Stack : CSS,JavaScript
Close #923
Now on click of the hamburger icon , the navbar appears properly.And also made this navbar responsive for smaller devices.
https://github.com/apu52/Travel_Website/assets/143121854/3899253c-13cd-43d3-90cd-36df2770c54b
I have made this navbar on the rate us page responsive also.
Yes GSSOC'24
> fix: Now navbar id displayed on click of the hamburger on the rate us page.

- feedback.html
Title :  [Bug]: On the "Rate Us?" page, clicking on nav__logo doesn't send you back to #Home
Issue No. : #939 
Close #939 
Made the nav__logo on feedback.html page link to the home page(index.html).
https://github.com/apu52/Travel_Website/assets/20481489/80fb5992-ef2a-4b7d-87dd-e6973132fd25
> fix: fixed nav__logo link on feedback page

- package.html
- styles.css
Close #886 
Code Stack : 
HTML, CSS , JS used 
created a pop up for discount for trip packages webpage. The pop up appears after 5 seconds of loading the webpage to appear it as a pop up. Also a close button is also available in the top right corner to close the pop up.
Please tell if any changes required.
> feat: Created a pop up for discount for trip packages webpage

- thankyou.css
- thankyou.html
Fixed issue: #1006 
Title : #1006 
Issue No. : #1006 
Close #1006 
This pull request improves the visual design of the thankyou.html page to enhance the user experience following feedback submission. The updates include:
- Aesthetic enhancements to make the page more engaging and visually appealing.
- Refinements to the user interface for a more pleasant post-feedback interaction.
https://github.com/apu52/Travel_Website/assets/159511364/8244d236-ad88-4b48-9ce3-8b2aedffd181
> feat: Enhance Visual Appeal of thankyou.html Page

- login.css
Title : Text is overlapping in the sign up page.
Issue No. :  #1001
Close #1001
I have made changes in the CSS and now the text on the left is not overlapping .
Yes
> fix: Text overlapping on the sign up page is solved.

- index.html
Title : Added website visitor widget in the footer 
Issue No. : #853 
As mentioned in the issue #853 assigned, I have added a website visitor widget to the website page and the pictures are attatched for your reference.
**Before:**
**After:**
> feat: Created A website visitor Widget 

- index.html
- styles.css
Title : Image is overlapping in the Tourist Guide section
Issue No. : #1032
Close #1032
Fixed the overlapping of image in Tourist Guide section with the testimonials section .
Yes under GSSoC'24.
> fix: Fixed the overlapping of image in Tourist Guide section.

- feedback.html
Title :  [Bug]: On the "Rate Us?" page, clicking yet again on the "Rate Us?" link in the NavBar sends you to a stray route.
Issue No. : #940
Close #940 
https://github.com/apu52/Travel_Website/assets/20481489/e82ec4c9-8552-4272-8dab-eb71b9da99d4
> fix: fixed feedback link on the feedback page itself

- faq-website.css
- faq.html
- styles.css
Title :Navbar on the FAQ's page is not proper in responsive view.
Issue No. : #1002
Close #1002
I have modified the navbar on the FAQ's page . Now this navbar is properly aligned for various devices.
Yes GSSoC'24.
> feat: Modified navbar on the FAQ's page for responsive view .

- pricing/style.css
Issue No. : #831 
Code Stack :  CSS
Close #831 
To make the text visible in membership page, I changed the styling of the page.
Please add level to this issue.
> fix: Text fully visible in membership page

- faq-website.js
- faq.css
- faq.html
Title : Improved UI of FAQ page to match website theme
Issue No. : #986
Code Stack : 
Close #986
Improved UI to match website theme by adding transition and animation.
Made the page responsive too.
> feat: Improved UI of FAQ page to match website theme and responsive

- index.html
Title : style: Subscribe Button CSS Updated
Issue No. : #1052
Code Stack : 
Close #1052 
I have updated the css of the the subscribe button and the input .
> style: Subscribe Button CSS Updated

- plantrip.html
Title : Trip Planner page UI 
Issue No. : #1054
Code Stack : 
Close #1054
Improved the UI of trip plan page to match website theme.
Made the page responsive too.
Added pop-up on submission of form.
https://github.com/user-attachments/assets/22179d26-6e32-4c7c-a275-c5297838ac7f
> feat: Trip Planner page UI 

- styles.css
Title : Added dark-theme in testimonials
Issue No. : #1056
Code Stack : 
Close #1056
Added dark-themes for the testimonials section that would go with dark-mode
> fix: Added dark-theme in testimonials

- styles.css
Title : navbar hover bug solved
Issue No. : #1075 
Code Stack : #1075 
The navbar hover is not working properly the underline in hover is coming outside navbar so i fixed it in css navlinks a:hover in styles.css
now the underline comes just under the navbar components
> feat: navlinks a:hover css added

- contributors.css
- contributors.html
- contributors.js
- index.html
Title : Added the contributors page
Issue No. : #1049 
Code Stack : 
Close #1049 
Added a contributors page which display project contributors
https://github.com/user-attachments/assets/e4c6a35b-b8a5-43e0-92ed-05796a5593b6
GSSOC'24
> feat: Added the contributors page

- Adventure.html
Title : Improve Adventure Page 
Issue No. : #1112
Code Stack : HTML CSS JS
Close #1112 
- Added search bar and it's respective JS
- Added filters relevant to adventure page
- made flex box to add icons and rating in one row
- Added icons for each place
- Search bar icon modified
> feat: Updated Adventure Page

- pricing/index.html
- pricing/style.css
Title : Fixed Hamburger
Issue No. : #1093
Code Stack : 
Close #1093
The Hamburger now works in the Membership page
> fix: Fixed Hamburger

- story.html
Hey @apu52 
-  issue closes #1027 
I have enhanced the UI and fixed the bug in the story page
> feat: UI Enhancement and Bug Fixed in Story Page

- 404.html
Title : [Bug]: Home button reloads the page and doesn't take to home page 
Issue No. : #1034 
Close #1034 
I opened the browser and inspected the issue, then I added the best possible solution.
https://github.com/user-attachments/assets/c9082b6c-7259-4e54-b1a9-20bb1a1cc29c
> fix: error page and home page connected.

- login/login.css
- newLogin.html
Title : hover on social icons in login
Issue No. : #1108
Code Stack : html css
Close #1108
add hover on social icons of login page 
https://github.com/user-attachments/assets/23080428-078f-4dd2-a690-b6a2bda1b7fd
> feat: hover on social icons in login

- faq.html
- feedback.html
- index.html
- privacy.html
- tnc.html
Hey @apu52 
- issue fixes #1141 
I have fixed The cursor. The Trail effect is hidden in Mobile View
> feat: The cursor Trail effect hide in Mobile View

- index.html
Title: Working of Chatbot fixed
Issue No. :  #1037 
Earlier the chatbot wasn't working at all. It was giving an error that the chatbot is unavailable. Now I have created a chatbot that is able to answer user queries using the given knowledge base as well as AI.
Before changes
After changes
https://github.com/user-attachments/assets/0eb07c41-88fc-4142-be4d-74441d197f45
> fix: Working of Chatbot fixed

- index.html
Title : Centered para
Issue No. : #1149
Code Stack : 
Close #1149
> fix: Centered para

- index.html
- package.html
Title : Footer of Trip Package page fixed
Issue No. : #1105
Code Stack : 
1. Added Social media icons.
2. Added google translator.
3. Map for address location.
4. Alignment issue of text.
5. Responsive footer for all screen size.
> fix: Footer of Trip Package page fixed

- privacy.html
- tnc.html
Title : Two touguides logos on the T&C page .
Issue No. : #1132
Code Stack :  HTML,CSS
Close #1132
I have also updated the mofified the color of Privacy Policy heading in Privacy page and made it similar to T&C page . 
Yes
> feat: Removed the duplicate Tourguide logo on the T&C page .

- hotel.html
Title : UI of Hotel Booking Form and responsive
Issue No. : #1125
Code Stack : 
Close #1125
Improved UI to match with website theme.
Added pop-up on submission of form.
Navigation button to home page.
Made the page responsive for all screen size.
https://github.com/user-attachments/assets/0a764a3b-b0aa-4b34-8509-b6c44d968076
https://github.com/user-attachments/assets/aa4a580d-02ef-43ec-8372-6224fdf6e08a
> feat: UI of Hotel Booking Form and responsive

- index.html
fix: Wrong Hover Animation #1071 
Title :
Issue No. : #1071
Close #1071 
Fixed hover animation
> fix: fixed hover

- index.html
- style_.css
- styles.css
Title :
Issue No. : #1136 
Code Stack :  HTML CSS
Close #1136 
- Fixed the overline issue on navbar
- Removed other CSS bugs and index.html bugs
> fix: Fixed Overline in NavBar

- HoneyMoon.html
Title : Improved Honeymoon page
Issue No. : #1181 
Code Stack :  HTML CSS JS
Close #1181 
- fixed alignment
- Search bar icon modified
- Added search bar and it's respective JS
- Added filters relevant to adventure page
- Made flex box to add icons and rating in one row
- Added icons for each place based on their speciality
> feat: Updated HoneyMoon page

- story.html
Title : Wrong logo of the website in story page
Issue No. : #1102 
Close #1102 
Currently, in the story page of the website wrong logo of the website is being displayed in the navbar. 
I have updated it to the new logo.
I am contributing under `GSSOC'24`
> fix: update logo in story page

- index.html
Text not visible in dark mode #1179
Issue No. : #1179 
Close #1179 
Watch our story text is visible in dark mode and fixed 
> fix: fixed story text

- Adventure.html
- Cultural_Exp.html
- HoneyMoon.html
- index.html
Title : Old twitter logo in the footer . 
Issue No. : #1134
Close #1134
I have added new twitter logo with suitable hover effects  on the footer of home page , honeymoon , adventure , cultural experience pages where old twitter logo was present . 
Yes
> feat: Added new twitter logo in footer of all pages .

- styles.css
Title : _Fixed email subscription box colour issue in dark-mode_
Issue No. : #1183 
Close #1183 
- Fixed email subscription box colour issue in dark-mode using CSS.
- Now, the email box will look good in dark-mode as well.
_Please review and merge my pull-request under GSSoC'24_
Yes, GSSoC'24
> fix: email subscription box colour issue in dark-mode

- index.html
Title : Added Cookie Pop-up to the Website
Issue No. : #1126
Code Stack : 
Close  #1126
Added Cookie Pop-up to the Website, included the paragraph to understand the concept.
It is responsive too
https://github.com/user-attachments/assets/8244b4cb-a467-4e99-a773-97f6e8d7a1f4
> feat: Added Cookie Pop-up to the Website

- contributors.css
- contributors.html
Title : Add a scroll to top button on the contributor page. 
Issue No. : #1219
Code Stack : HTML,CSS,JavaScript
Close #1219
Added a scroll to top button on the contributor page which on click scrolls to the top with a smooth scroll effect .
https://github.com/user-attachments/assets/beb7c2ff-c6ee-4410-980b-36a4a9172042
Yes
> feat: Added a scroll to top button on the contributor page .

- index.html
Title : Video in About Us section
Issue No. : #1124 
Close #1124 
Video in About Us section on Tourguide
> feat: Added Video

- index.html
- styles.css
Title : Improve Navbar Visibility
Issue No. : #1129
Code Stack : 
Close #1129
- Enhanced navbar visibility with better readability and contrast.
- Added a dropdown menu for better organization.
**Before**
**After**
Yes, GSSOC'24
> feat: Improve Navbar Visibility and Add Dropdown Menu

- index.html
- styles.css
Title : Footer page Select Language Enhancement
Issue No. :#1224
Code Stack : 
Close #1224
In footer Google icon size increased , Select Language box size increased and color changed.
Before:
After:
> fix: In footer Google icon size increased , Select Language box size increased and color changed.

- blog.css
- blog.html
- index.html
Title : Added filter blogs option
Issue No. : #1206
Code Stack : HTML, CSS and JS
Close #1206
Added
- filter functionality to blog categories
- a reset button
- smooth transition between filter and reset
https://www.awesomescreenshot.com/video/29952216?key=de10ee3a45170d004bec0c814de7cd57
> feat: Added filter blogs option

- blog.css
Title :Text not visible on hover of orange tabs on blogs page .
Issue No. : #1218
Close #1218
Text is now visible on hover of the orange tabs . I have changed the color on hover , so that it is visible properly .
Yes
> fix: Text is now visible on hover of orange tags and button on blogs page .

- privacy.html
Title : Styled the privacy page
Issue No. : #1250 
Code Stack : html, css
Close #1250
Before
After
https://www.awesomescreenshot.com/video/29991852?key=1a73e1d39620da0f52c8d45630549300
> feat: Styled the Privacy page

- index.html
Title : Testimonials Section Enhancement
Issue No. :#1061
Close #1061 
Added flipping card feature in testimonials section.
https://github.com/user-attachments/assets/f4c2aadc-329b-466b-99d3-3002f78b316c
> feat: Testimonials updated

- index.html
Text not visible on landing page #1208
Title :
Issue No. : #1208 
Close #1208 
Now text is properly visible on landing page
> fix: Text not visible on landing page

- footer.css
- index.html
- styles.css
Title :  Resolved Footer UI Issue
Issue No. : #1276 
Code Stack :  HTML, CSS
Close #1276 
I updated the previous Footer UI, and Enhanced the UI for better visiblity, and fixed some existing issues.
Well spacing between elements and make it to match proper sites UI.
Prev:
New:
I updated the previous Footer UI, and Enhanced the UI for better visiblity, and fixed some existing issues
> feat: Improved Footer Design 

- index.html
Title : Add redirections to the buttons in footer page
Issue No. : #1278 
Close #1278 
Adding redirection to the buttons linkedin, github, etc in footer page 
https://github.com/user-attachments/assets/41fec1f7-25ae-481b-a18f-a75433a31f95
- [] Feature enhancement
- [] Documentation update
- [] Other (specify): _______________
> fix: Add redirection to the buttons linkedin, github, etc in footer page #1278

- explore.css
- styles.css
Title : _I want to make home page responsive_
Issue No. : #1290 
Close #1290 
- Made the home page responsive using css media-queries.
- Now, the home page will look responsive in mobile-view as well.
https://github.com/user-attachments/assets/3228ce11-b1dc-4400-bdf9-394312394a27
_Please review & merge this pull-request under GSSoC'24_
Yes, GSSoC'24
> fix: Made the home page responsive for mobile-view

- Adventure.html
Title :  dark mode in adventure page
Issue No. : #1215
Code Stack :  html css j
Close #1215
dark mode in adventure travel page 
https://github.com/user-attachments/assets/6b29cebc-1187-4226-ab0f-8a2b26274fcc
> feat: dark mode in adventure travel  page

- dedicated-destinations/Dubai/Dubai.css
- dedicated-destinations/Dubai/start.html
- dedicated-destinations/Goa/Goa.css
- dedicated-destinations/Goa/start.html
- dedicated-destinations/London/London.css
- dedicated-destinations/London/start.html
- dedicated-destinations/Maldives/maldive.css
- dedicated-destinations/Maldives/start.html
- dedicated-destinations/Paris/Paris.css
- dedicated-destinations/Paris/start.html
- dedicated-destinations/bali/bali.css
- dedicated-destinations/bali/start.html
- dedicated-destinations/brazil/brazil.css
- dedicated-destinations/brazil/start.html
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_start.html
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_tour.css
- dedicated-destinations/kashmir/kashmir.css
- dedicated-destinations/kashmir/start.html
- dedicated-destinations/machu-picchu-peru/Machu_start.html
- dedicated-destinations/machu-picchu-peru/Machu_tour.css
- dedicated-destinations/new-york/NewYork.css
- dedicated-destinations/new-york/start.html
- dedicated-destinations/santorini-aegean-sea/start.html
- dedicated-destinations/santorini-aegean-sea/tour.css
Title : Added dark theme for all 12 best trip package pages
Issue No. : #1262 
Code Stack : HTML ,CSS, Javascript
Close #1262 
- Added dark theme for all the 12 destination pages of best trip package
- Modified shadow effects for better visibility in dark mode.
- Adjusted button and interactive element styles for dark mode compatibility.
- Ensured contrast and readability in dark mode for all text elements.
https://github.com/user-attachments/assets/80f17aa6-0b82-4400-ac82-5631866dd829
> feat: added dark theme for all trip package pages

- Licensing.html
- privacy.html
- tnc.css
- tnc.html
Title :Add scroll to top button on Privacy Policy , T&C , Licensing pages .
Issue No. : #1288
Code Stack : HTML,CSS,JavaScript
Close #1288
Added a working scroll to top button on privacy , licensing , T&C pages . 
Yes
> feat: Added a working scroll to top button on privacy , T&C and licensing pages .

- contributors.css
- contributors.html
- contributors.js
Title : add dark mode in contributors page
Issue No. : #1210
Code Stack : html css and js 
Close #1210 
dark mode feature in contributors page 
https://github.com/user-attachments/assets/9f40ebe6-eecb-414f-818a-7122315cf6db
> feat: Dark mode in contributors page

- plantrip.html
Title : Updated plan a trip page
Issue No. : #1261
Close #1261 
> feat: Update plantrip.html

- Adventure.html
- Cultural_Exp.html
- HoneyMoon.html
Title :
Issue No. : #1321 
Close #1321 
- Added dark mode to all the three pages mentioned in the issue
- Added dark-mode CSS to each component as required
- added missing JS script in two pages
> feat: Dark-mode of Three pages added

- feedback.html
- newLogin.html
Title : 404 error when clicked on log in button from feedback page . 
Issue No. : #1294
Close #1294
Now no error page when clicked on log in button from feedback page .
https://github.com/user-attachments/assets/eca61b62-9b0d-4328-bb55-21fc7bb6fc76
Yes
> feat: No error when clicked on log in button from feedback page .

- styles.css
Title : _Made the X icon of footer black on hover._
Issue No. : #1319 
Close #1319 
- I have fixed the colour issue of X (Twitter) icon of footer while hover.
- Now the X icon will become black when hovered.
https://github.com/user-attachments/assets/1df6486a-da3c-4362-9f36-91f0f1057250
_@apu52 Please review & merge my pull-request under GSSoC'24_
Yes, GSSoC'24
> fix: Made the X icon of footer black on hover

- feed.html
Title :  _Added social media profile urls in feedback page_
Issue No. : #1364 
Close #1364 
- Added social media profile urls in feedback page.
- Now, the social media profiles will open when clicked on these icons.
https://github.com/user-attachments/assets/60a8fcb3-28c4-4379-8f07-d06543f4e248
@apu52 please review & merge my pull-request under GSSoC'24
Yes, GSSoC'24
> fix: Added social media profile urls in feedback page.

- privacy.html
- tnc.css
- tnc.html
Title :Add light / dark mode effect in Privacy and T&C Pages.
Issue No. : #1272
Code Stack : HTML,CSS,JavaScript
Close #1272
Added a toggle button which toggles the theme of the website.
Yes
> feat: Added light dark mode toggle feature on T&C and privacy pages .

- counter.css
- index.html
Title : Fixed hero section for mobile screen 
Issue No. : #1240 
Code Stack : 
Close #1240 
Fixed for mobile screen
> fix: Fixed hero section and others of home page for mobile screen

- topdeals/topdeals.html
Title : added links to book now button
Issue No. :#1363
Close #1363 
> feat: added changes to link topdeals

- loader.css
Title : Chatbot Visible During Preloader. 
Issue No. : Fixes #996 
Fixed Chatbot Visible During Preloader. 
https://github.com/user-attachments/assets/e0d36b76-27c1-4a7a-aab5-1634b7d68c2b
> fix: Fixed Chatbot Visible During Preloader 

- Licensing.html
Title : restyled the privacy policy page
Issue No. : #1296
Close #1296
https://www.awesomescreenshot.com/video/30378708?key=3cbf4a73677dc849c11b1b81eb303ef0
> feat: restyled the privacy policy page

- read.html
Title :
Issue No. : #1361
Code Stack : css
Close #1361
> feat: Update read.html

- healt.html
Title : Health and safety alerts
Issue No. : #1333 
Close #1333 
Added health and safety alerts
> feat: Added Health Alerts

- index.html
- membership.css
- membership.html
Title :
Issue No. : #1382
Code Stack :  HTML CSS JS
Close #1382 
- NEW PR redo
> feat: Improved membership option page

- trending.css
- trending.html
Close #1440
Background Update: Added a distinct background section for an improved visual effect, enhancing the page’s aesthetic.
Header and Subheader Styling:
Changed the main heading to a prominent black color for better readability.
Added a descriptive subheading to inspire confidence and provide an inviting overview of the tours.
Tour Card Layout:
Organized destinations into individual, uniform cards with images, names, and links for a cleaner and more structured presentation.
Buttons for Easy Navigation:
Added a Blog Page button on each card for quick access to detailed blogs on individual destinations.
Included a View all tours button to lead users to the full list of tour packages.
Responsive Design:
Structured the page for compatibility across various devices, ensuring a smooth …
> feat: enhancement of trending page

- Image-Gallery/style.css
- Image-Gallery/stylecaptions.css
- loc.html
Title :
Issue No. : #1527
Code Stack : 
Close #1527 
Fix button styles and improve UI with color coordination (Purple and Dark Blue Theme)
> fix: Changed colour code and basic functions of the code (basically css)

- newLogin.html
Title : Solved issue on newLogin.html, where numbers were sent to database in name field.
Issue No. : #1390 
Code Stack : Javascript
Close #1390 
In the registration page, number can be inputted into the db. So I used JavaScript validation to solve the issue. 
Now only letters can pass through.
GSSOC 2024 Extended and Hacktoberfest 2024
> fix: on name validation, issue #1390

- backend/src/controllers/user-controller.js
Code Stack: Node.js, Express.js, MongoDB (assuming based on the use of User model)
Close #1407
This change requires updating the bcrypt package in package.json and potentially updating the User model to accommodate longer password hashes. Existing users' passwords will need to be rehashed if implementing these changes in a live system.
> feat: Add bcrypt password hashing and salting for secure authentication

- README.md
This PR updates the README file for the **TourGuide** travel website, reflecting recent enhancements and improvements made to the project.
*   **🌈 Added Rainbow Line**: Included a colorful rainbow line to enhance the visual appeal of the README and create a more engaging introduction to the project.
*   **🔄 Updated Language Icons**: Replaced existing language icons with new, more appealing versions to better represent the languages offered on the website.
*   **🌟 Revamped Features Section**: Reorganized and enriched the features section with clear descriptions and attractive formatting to highlight the key offerings of the travel website.
*   **🖼️ Enhanced Visual Presentation**: Made additional aesthetic improvements throughout the README to ensure it aligns with the vibrant theme of the …
> fix: Update README #1475

- index.html
fix : #1471 Improvement in testimonial section
#1471 : 
Title :Improvement in testimonials section.
Issue No. : #1471 
Close #1471 
I  have implemented a rating system on the testimonial cards for my project, and I ensured that it is mobile-responsive as well.
https://github.com/user-attachments/assets/0030289a-5635-4175-8208-a2bf4980efb6
> fix: testimonial page Responsiveness and ratings added

- plantrip.html
Title : feat: added suggestions of places while entering locations (fixes issue #1445)
Issue No. : 1445
Code Stack : plantrip.html
Close #1445 
I have added suggestions of lot of destinations to have a smooth conduct of filling a form and not misinterpreting the destinations by one filling the form. This addition will be beneficial for people who don't know much about destination or places.
Kindly review my PR.
https://github.com/user-attachments/assets/64eda5f3-c359-4a67-8f46-70630bf7e016
> feat: added suggestions of places while entering locations (fixes issue #1445)

- index.html
#Font Styles updated
Title :  Refactoring css and font
Issue No. : #1436
Code Stack :  CSS , HTML
Close #1545
Improved font styling and css
> refactor: font styles

- newLogin.html
#checkPassword function is included in js
Title : Strong Password Recommendation
Issue No. : #1484 
Code Stack : Html, css, JS
Close #1484 
Password Strength Checker: The checkPasswordStrength function evaluates the password's strength based on its length and the presence of uppercase letters, lowercase letters, numbers, and special characters. A message is displayed to guide the user on password strength((e.g., uppercase letters, lowercase letters, numbers, special characters, and minimum length))
Password Validation: The form validation prevents users from registering or logging in with weak passwords or invalid input.
https://github.com/user-attachments/assets/0a735119-a748-4077-a7b6-14d9b61b0c88
> build: Strong Password indicator

- index.html
#1512  
Title :
Issue No. : #1512 
Code Stack : 
Close #1512 
Added hover effect to the icon
https://github.com/user-attachments/assets/fd07e900-dd79-4697-a16d-71a35eecde71
> feat: Added hover effect on 2nd button of home page ie. plan a trip

- styles.css
Title : Unnecessary spacing above navbar
Issue No. : #1400 
Close #1400 
Fixed navbar top transparent bug
> fix: fixed navbar bug

- topdeals/topdeals.html
#1539 
Title : Add hover effect in top deals cards
Issue No. :#1539
Code Stack : 
Close #1539
Add hover effect on the top deals cards .
https://github.com/user-attachments/assets/5eee3a3e-ec86-4b48-bfab-cf1be1326e90
> feat: Add hover effect in top deals cards

- feedback.html
Title : Issue with Navigation Links on "Rate Us?" Page Opening New Tabs
Issue No. : #1513 
Close #1513 
Fixed the navigation bar links on the "Rate Us?" page, which previously opened in new tabs. Links now open in the same tab for a seamless, consistent browsing experience across all sections.
before fixing the bug-
https://github.com/user-attachments/assets/676a0fbd-2c36-4413-971d-4f98dd279046
after fixing the bug-
https://github.com/user-attachments/assets/0001a5c8-023a-4dc8-a11a-a51c8de0d834
Removed target="_blank" from navigation links, allowing pages to load in the same tab. Confirmed smooth navigation across all sections from "Rate Us?" and other pages.
Manually tested each link to ensure they open in the same tab, maintaining consistent navigation across the site.
@apu Please …
> feat: modified rate us page

- index.html
Title : Made the changes on the navbar according to the changes mentioned.
Issue No. : #1578 
Close #1578 
> feat: Made the changes on the navbar according to the changes mentioned. #1578

- index.html
Title : Double scroll bar in the  website#1572 
Issue No. :#1572
Close #1572
Codestack: CSS
There was double scroll bar in the website which affects the overall UX by adding unnecessary space and redundant scrolling has been resolved.
https://github.com/user-attachments/assets/c0b789f0-737b-4231-b7c2-3335c45a965c
> fix: Double Scroll bar

- index.html
- sitemap.css
- sitemap.html
Title : Created Site Map Page
Issue No. : #1568
Code Stack : 
Close #1568
This pull request introduces a comprehensive site map for the project. The site map includes links to all relevant pages and resources within the application. This will enhance user navigation and improve search engine optimization (SEO).
**Created a new file:** A new file named `sitemap.html` and for styling `sitemap.css` is created.
The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.
https://github.com/user-attachments/assets/775dc44e-b965-468d-96a6-3ce77cee2419 …
> feat: Created Site Map Page

- 404.html
> fix: issue is resolved

- styles.css
Title :Fix: Fixed button UI issue in 'Best Trips Package' and 'Home' Section.
Issue No. : #1579 
Code Stack : 
Close #1579 
Fix: Fixed button UI issue in 'Best Trips Package' and 'Home' Section where the underline comes under button in other buttons but for these button the underline comes under text.
https://github.com/user-attachments/assets/07b08955-23d9-4c20-9be2-55c353005b13
> fix: Fixed button UI issue in 'Best Trips Package' and 'Home' Section.

- about.html
- index.html
- packages.html
- payment.html
- topdeals/topdeals.html
Issue No. : 1597
Code Stack : 
Close #1597 
Fixed several broken links 
about page to home page
All modules in services
Book now in pricings
so on and i will try to fix other broken links also
https://github.com/user-attachments/assets/dc11a055-608d-409e-8bde-e45589d5e9e6
Uploading travel_website.mp4…
I have identified and fixed multiple broken links within the project and addressed errors on view pages. Please refer to the description above for specific issues and solutions.
> fix: Multiple Broken Links, Errors on View

- about.html
Title : About US page is not redirecting
Issue No. : #1561
Close #1561 
Fix the redirection link from About Us page to the Home page and the Start journey buttons now redirected to Login page.
https://github.com/user-attachments/assets/c2a6e59d-20f9-4a7b-80e3-f68388332de2
> fix: About US page is redirected to Home page

- index.html
- offline.html
- service-worker.js
Title :Offline First Experience with Caching and Sync Status Indicator
Issue No. : #1592 
Code Stack : Html css and js
In today’s digital environment, users often encounter connectivity issues, which can disrupt their interaction with a website or application. Implementing an "Offline First" approach could greatly improve user experience, especially for those accessing the platform in areas with intermittent internet access. 
The idea is to integrate offline support in the app, ensuring users can still browse core content and access cached data even when they temporarily lose connectivity. By using service workers to cache essential assets and certain frequently accessed data, we can ensure that the application remains accessible and performs smoothly offline. Additionally, we’ll …
> feat: Offline First Experience with Caching and Sync Status Indicator

- packages.html
Title : Enhanced styling of packages page
Issue No. :  #1610 
Code Stack :  html, css
Close #1610 
This PR introduces a comprehensive redesign of the packages page to improve the overall user experience and visual appeal. The new styling enhances readability and interaction, making it easier for users to navigate and understand package details.
https://github.com/user-attachments/assets/7e46bf85-d507-46a8-8fb1-840bd0026285
> feat: Enhanced styling of packages page

- faq.html
Title : FAQ dark-mode heading
Issue No. : #1638
Code Stack : 
Close #1638 
In dark mode, title was not visible of faq, 
also, the accordion icon was not visible clearly in any mode.
Before:
After:
> feat: faq changes - dark mode title

- footer.css
- index.html
Title : Improvement of footer Section
Issue No. : #1483 
close #1483 
The footer was refined by adjusting section spacing, resizing the map, increasing copyright text size, and compacting social media icons. The visitor box was slightly reduced, the language box color now matches the footer background, and the support section was standardized for a cohesive look.
> fix: improvement of footer section

- index.html
Title : Improvement needed for button appearance on home page
Issue No. : #1463
Close #1463
Enhanced the UI of homepage buttons by implementing hover effects, including size scaling for a dynamic interaction and subtle color transitions in the box shadow for improved visual appeal.
- [ X] I have performed a self-review of my code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have gone through the  `contributing.md` file before contributing
- [ X] I have Starred the Repository.
- [ X] I am …
> fix: Improvement of button appearance on home page

- trending.html
Title : Improved UI of TrendingTour page and make it responsive 
Issue No. : #1663
Code Stack : Html, CSS, Js
Close #<1663>
I made a **NEW TRENDING TOURS PAGE** which is polished, professional design aligns perfectly with contemporary web standards, delivering an immersive and visually appealing experience
And **YES it's also responsive** :) _[as shown in image]_
KWOC 2024
> feat: Improved UI of TrendingTour page and make it responsive

- contributors.css
- index.html
- navLinks.css
- style_.css
- styles.css
issue #1680
Title :  Improve Navbar Hover Effects
Issue No. : 1680
Close #1680
This PR enhances the hover effects for the navigation bar by:
Adding a smooth fade-in and fade-out effect for better aesthetics.
Maintaining suitable colors in dark and light mode.
Ensuring the dropdown under "Services" appears smoothly with a fade effect.
Smooth navigation of buttons with 3D Glow & Translucency.
Adding a glow effect behind the navbar for 3D effect.
https://github.com/user-attachments/assets/c115bd3b-d003-440a-a354-523347cbe845
Before: 
After enhancement: 
This contribution is intended to enhance the color and hovering effects on navbar. 
> feat: Fixed hover effect on navbar 

- package.html
- payment.html
- story.html
Title : [Bug]: package.html Footer twitter logo update
Issue No. : 1650
Close #1650 
This pull request includes updates to the social media icons and links in multiple HTML files, as well as a change to the CSS library used in `story.html`. The most important changes are listed below:
Updates to social media icons and links:
* [`package.html`](diffhunk://#diff-b390e7110fda8d043f09576389d4d43d0ef007f8e7203a673b5864ffd4c044b7L891-R891): Updated the Twitter icon class to `fab fa-x-twitter` to reflect the new branding.
* [`payment.html`](diffhunk://#diff-e1e819d0325b5f2ed47d2dda603e6407e0fd0813bf56ac3d10121274e1262d8eL467-R469): Updated the Twitter icon class to `fab fa-x-twitter` and added a link to the specific Twitter profile `https://x.com/ArpanCh40193288`.
* …
> fix: Update package, payment and story pages to reflect new X branding 

- navLinks.css
Title : Collapsible Navbar made scrollable
Issue No. : #1717 
Close #1717 
This PR fixes the issue where the collapsible navbar was not scrollable. The update ensures that when the navbar contains multiple menu items, it becomes scrollable instead of overflowing off-screen.
https://github.com/user-attachments/assets/3e1981b6-80b0-4b51-9688-1bc2819194d0
> fix: Collapsible Navbar made scrollable

- about.css
- about.html
[Enhancement]: Enhancing the About Us Page with an Interactive Growth Timeline #1712 
Title :Enhancing the About Us Page with an Interactive Growth Timeline 
Issue No. : #1712 
Code Stack : HTML , CSS
Close #1712 
This PR enhances the About Us page by implementing an interactive growth timeline, visually showcasing TourGuide's journey and key milestones. The timeline is designed to provide a smooth, engaging, and responsive user experience while maintaining accessibility and a modern UI.
https://github.com/user-attachments/assets/52a4867d-c1ce-4f57-910e-c3d56ecae1ba
> feat: Enhancing the About Us Page with an Interactive Growth Timeline #1712

- about.css
- about.html
Reverts apu52/Travel_Website#1721
> Revert "feat: Enhancing the About Us Page with an Interactive Growth Timeline #1712"

- about.css
- about.html
**Title : Improved Responsiveness and Visual Enhancements for Growth Timeline Section**
Issue No. : #1721 
Code Stack : HTML, CSS,JS
Close #1721 
**Enhanced the responsiveness and layout of the "Our Growth" timeline section for better mobile compatibility. Added media queries to reposition timeline icons and content. Adjusted font sizes, spacing, and alignment for smaller screens to improve readability and user experience.**
*Please find attached screenshots or a video demonstrating responsive layout behavior and new timeline design on mobile view.*
The changes aim to ensure the timeline and growth counters are fully functional and visually appealing on all screen sizes, especially on mobile devices.
> feat: Improved Responsiveness and Visual Enhancements for Growth Timeline Section

- about.html
- feedback.html
- index.html
- package.html
- topdeals/topdeals.html
Title :feat: Implemented clickable logo navigation
Issue No. : #1698 
Code Stack : 
Close #1698 
made the logo clickable so that when we click it is navigates to home page 
> feat: Implemented clickable logo navigation

- footer.css
- index.html
Title : Fix: Footer Layout Fixed
Issue No. : #1718 
Close #1718 
This PR fixes the footer layout issue across all screen sizes. Previously, the footer had alignment inconsistencies and responsiveness problems on smaller screens. The updated layout uses Flexbox/Grid for better structure, spacing, and alignment. Media queries were also added to ensure proper responsiveness.
https://github.com/user-attachments/assets/236a4aef-95fd-4685-8d34-253c905ef761
> fix: Footer Layout Fixed

- .vscode/settings.json
- feed.css
- index.html
- pricing/style.css
- style.css
- trending.css
Title : Update the button
Issue No. :  #1704 
Code Stack :  CSS Changes
Close #1704 
<--Enhance the chatbot button by adding effects, transition.
- [yes ] Feature enhancement
- [ yes] I have performed a self-review of my code.
- [ yes] I have tested the changes thoroughly before submitting this pull request.
- [ yes] I have Starred the Repository.
<--Apertre2.0-->
> feat: Made the changes
