- package.html
Hello PA,
Fixed Issue Number: #540 
**Attachment**
Now the "_Contact Us_" button in the footer section of Package page is navigating to contact form
> Fixed "Contact Us" button issue! #540 

- plantrip.html
Title : Date Validation for Plan a trip page
Issue No. : #611 
Code Stack : HTML | JS
Close #611 
**Before Date Validation**
**After Date Validation** 
(If an earlier date is selected an alert message is popped up)
(For a future date)
**Additional context**
The date is validated in Plan a trip page. The trip won't get planned for a past date. 
I am a GSSOC'24 Contributor
> Added Date Validation to Plan a trip page #611

- .vscode/settings.json
- feed.css
- feed.html
Title :Enhanced feedback form .
Issue No. : #665
Code Stack : 
Close #665 
Please merge it and assign it a label under Gssoc'24.
- [ x] Feature enhancement
- [ x] I have performed a self-review of my code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have gone through the  `contributing.md` file before contributing
Yes , GSsoc'24
> enhanced feedback form

- index.html
Adding a google translate page
Changed the index.html file to add the google translator feature at the footer of the website
Yes, GSSoC24
> Google translation page added

- Theme.js
- styles.css
Title: No Hover Effect on Subscribe Button and Theme Style Not Changing
Issue No. : #659 
Code Stack:  HTML, CSS, JS
Close #659
This pull request resolves two bugs with the subscribe button on the website that were identified earlier. I've fixed both problems, including adding a hover effect to the subscribe button and ensuring that its style updates appropriately when toggling the theme of the page.
https://github.com/apu52/Travel_Website/assets/98210910/2efe2a76-a672-408e-95e4-23a2a20f0d89
Yes, it is GSSoC 2024
> chore: Refactor theme toggle logic and update styles

- index.html
Title : Images added in the Explore top destinations section
Issue No. : #586 
Code Stack : HTML | CSS
Close #586 
Images for each of the destinations are added in the explore top destinations section. Along with it, the background of each card is added with the same image.
Since the old PR had merge conflicts this is a new PR. The old PR is #705.
*Are you contributing under any Open-source programme?*
I am a GSSOC'24 Contributor
> fix: Images added in the Explore top destinations section #586 

- index.html
- story.html
I have added the links to the E-mail as well as with the phone number, so that when user clicks on them he/she is prompted to his default e-mail client and calling app. I have made these changes on Story Page as well as on Home Page of the website. 
**Changes:**
- Added a `mailto:` link to the email address `tour@tourguide.com` on the Story Page and Home Page footers, so that clicking on it opens the user's default email client.
- Added a `tel:` link to the phone number on the Story Page and Home Page footers, so that clicking on it opens the user's default phone dialer or calling app.
Issue No. : #621
Close #621 
I was earlier facing branch conflict and after updating my forked repository I noticed that all other footer links (FAQs, Terms & Conditions, Privacy Policy, …
> feat: Added Email and Phone Links to Footer Section!

- dedicated-destinations/Dubai/start.html
- dedicated-destinations/Goa/start.html
- dedicated-destinations/London/start.html
- dedicated-destinations/Maldives/start.html
- dedicated-destinations/Paris/start.html
- dedicated-destinations/bali/start.html
- dedicated-destinations/brazil/start.html
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_start.html
- dedicated-destinations/kashmir/start.html
- dedicated-destinations/machu-picchu-peru/Machu_start.html
- dedicated-destinations/new-york/start.html
- dedicated-destinations/santorini-aegean-sea/start.html
Title : Underline removed from the logo in each of the links of the different destinations in the "Best trip package" page.
Issue No. : #587 
Code Stack : HTML | CSS
Close #587 
The underline in the each destination's logo is removed.
The underline in the logo in each of destinations is removed in "Best Trip Package" page.
*Are you contributing under any Open-source programme?*
I am a GSSOC'24 Contributor.
> fix: Underline in the logoname in the links of each destination of the "Best trip package" #587

- index.html
- loginPage.html
Title : 'Logout' Button After Registration
Issue No. : https://github.com/apu52/Travel_Website/issues/530
Code Stack : HTML | JS
Close #530 
[screen-capture (2).webm](https://github.com/apu52/Travel_Website/assets/151984867/01cb490c-52a8-4bb9-b72a-69b3718236e4)
The Logout button takes the user back to the Login Page.
This is under GSSOC'24
> fix: Add Logout button 

- index.js
Title : 
Uncaught Error where the variable had re-declaration
Issue No. : 793
Code Stack : -
JavaScript 
Close #793 
The error message "Uncaught SyntaxError:
redeclaration of let activeSlide" and "Uncaught SyntaxError: redeclaration of let slideInterval" indicates you're trying to declare a variable with the name activeSlide and slideInterval twice using the let keyword.
So I have declared the variable activeSlide only once and initialised slideInterval with value null.
So here I declared it once..You can see the error is solved.
GSSOC-24
> fix: variable assignment and initialization in index.js

- explore.css
Title : To fix border of "CONTACT US" image section in Dark Mode
Issue No. : #615
Code Stack :  CSS
Close #615
I have fixed the issue of border in "CONTACT US" image section in Dark Mode
##Are you contributing under any Open-source program?
Yes, I am contributing under GSSOC 2024.
> To fix border of "CONTACT US" image section in Dark Mode

- Theme.js
Hi @apu52,
Title : Dark mode gets turned off on refeshing a page
Issue Close #732 
I have resolved the issue to persist the dark mode preference across page refreshes using localStorage.
The changes ensure that the user's selected mode (dark or light) is maintained even after the page is refreshed.
Please take a look and review it.
- To make the dark mode preference persist across page refreshes, used "localStorage" to save the user's preference.
- Then Saved the theme preference in localStorage whenever the theme is toggled.
- and then Checked the saved theme preference when the page loads and apply it accordingly.
https://github.com/apu52/Travel_Website/assets/131389695/8a466c0e-1ac4-48fa-8408-a028b67f4988
GSSOC'24
Could you please …
> feat: Resolved Dark Mode Persistance Issue After refreshing

- feedback.js
Title :Accepts zero star ratings
Issue No. :745
Code Stack : Javascript
Close #745 
Added additional functionality to accept only non-zero ratings in the "Rate our Service" page.
Also, made sure that after successful submission, the ratings and feedback are set back to default settings(that is zero stars and empty feedback)
Contributing under GSSOC 2024.
Please assign corresponding level tag also.
> fix: Updated feedback.js to accept only non-zero ratings

- .vscode/settings.json
- index.html
- styles.css
Title : BUG : Background of Contact Us is not properly visible 
Issue No. : #736 
Code Stack :  
HTML,CSS,JS
Close #736 
- The box shadow provides a subtle inset shadow at the top and a bottom shadow to the container.
- Applied to enhance the visual appeal and distinguish the container in the dark theme.
- Shadow values adjusted for optimal appearance and consistency with the theme's design language.
- The box shadow is scoped to `.dark-theme` class, ensuring it only applies to elements within a dark-themed container.
I am contributing under GSSOC'24.
> fix: Remove box shadow and update contact form styles

- payment.js
Updated payment html and javascript files to display total cost as per the selected package on the checkout page.
This does not affect the page or the website as a whole.
See #781
Title : Total amount remains same irrespective of the package selected #781
Issue No. : 781
Code Stack : JavaScript
Close #781
Updated and edited the payment html and javascript file, removing the static value and replacing it with the variable to update the total cost on the checkout page as per the selected package.
BEFORE CHANGE:
AFTER CHANGE:
Yes, I am contributing under GSSOC 2024.
> fix: Total amount remains same irrespective of the package selected #781

- index.html
- index.js
- styles.css
Title : Testimonial section into infinite Marquee
Issue No. : #743 
Code Stack : 
Close #743 
https://github.com/apu52/Travel_Website/assets/103347688/116b50c8-da7e-43d9-9b44-49ef8c4799c9
Please add the level label as well in the issue and PR. Thank you. 
GSSOC'24
> feat: Marquee effect in testimonial section

- styles.css
Hi @apu52,
closes #754 
considering the current positioning where the chatbot is in the rightmost bottom of the page and the scroll-to-top button is just above it, I adjusted the scroll-to-top button to be moved to the left side of the page to avoid overlap.
******Video/Screenshots (mandatory)******
Here as you can see :
Please take a look and also add required labels.
> fix: Fixing Overlap Between Chatbot and Scroll-to-Top Button

- dedicated-destinations/Dubai/main.js
- dedicated-destinations/Dubai/start.html
- dedicated-destinations/Goa/main.js
- dedicated-destinations/Goa/start.html
- dedicated-destinations/London/main.js
- dedicated-destinations/London/start.html
- dedicated-destinations/Maldives/main.js
- dedicated-destinations/Maldives/start.html
- dedicated-destinations/Paris/main.js
- dedicated-destinations/Paris/start.html
- dedicated-destinations/bali/main.js
- dedicated-destinations/bali/start.html
- dedicated-destinations/brazil/main.js
- dedicated-destinations/brazil/start.html
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_main.js
- dedicated-destinations/grand-canyon-national-park-arizona/Grand_start.html
- dedicated-destinations/kashmir/main.js
- dedicated-destinations/kashmir/start.html
- dedicated-destinations/machu-picchu-peru/Machu_main.js
- dedicated-destinations/machu-picchu-peru/Machu_start.html
- dedicated-destinations/new-york/main.js
- dedicated-destinations/new-york/start.html
- dedicated-destinations/santorini-aegean-sea/main.js
- dedicated-destinations/santorini-aegean-sea/start.html
Title : [Bug]: Climate for travel destinations is undefined
Issue No. : #895
Code Stack : JavaScript (imported axios and used apikey), HTML5
Close #895 
Imported Axios to get data using API key and added html tags to ensure that data is visible on website. Repeated this process for 12 cities.
- [ ✅] Bug fix
- [X ] Feature enhancement
- [ X] Documentation update
- [ X] Other (specify): _______________
- [✅ ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [ ✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ✅] I have gone through the  `contributing.md` file before contributing
##Are you …
> fix: Climate visible for destinations

- index.html
Title :  The destination section is not proper
Issue No. : #899 
Code Stack : 
Close #899 
Removed the extra images in the destination section
Before:
After:
> fix: Removed extra image in the destinations section

- faq-website.css
Title : Removed improper flickering of div elements
Issue No. : #861 
Close #861
when a client mouse over on the divs at Frequently Asked Questions Section are getting flickering due to improper sizing of divs and  hovering.
https://github.com/apu52/Travel_Website/assets/108344062/3c1c714c-4fe4-4a79-9c3d-7f37157927e2
Now I have removed the flickering effect and I adjusted the toggle button in such a way that there is no overlapping between the FAQ title(Questions)
https://github.com/apu52/Travel_Website/assets/108344062/0fc62e85-57b4-456a-96a9-23a294b97f24
> fix: Issue #861  Removed improper Flickering of elements

- index.html
- tilt.css
- tilt.js
Title : Addition Of 3d Parallax Tilt Effect on Cards 
Issue No. : #728
Code Stack : html,css,js
Close #728 
Added 3d parallax tilty effect on cards.
https://github.com/apu52/Travel_Website/assets/159264060/48bca623-b518-4d27-a962-7e1998b2a7ae
> feat: Added 3d parallax tilty effect on cards

- counter.css
- index.html
- index.js
- style.css
- styles.css
Title :
Issue No. : #911 
Code Stack : 
Close #911
https://github.com/apu52/Travel_Website/assets/146661411/a165d2a8-6ec2-4266-b6eb-57d661a18a5c
> feat: Counter added, Numeric status section improved

- counter.css
- faq-website.css
- faq-website.js
- faq.html
- index.html
- style.css
Title :
Issue No. : #909 
Close #909
- Added new accordion system to the page
- Added navabar
- Edited minute bugs in index.html file
- Also CSS for the FAQ page is done
https://github.com/apu52/Travel_Website/assets/146661411/d7752167-e4d3-49bd-8d06-9153859d8d9c
> feat: FAQ Page inproved

- index.html
- styles.css
Title : Footer Section alignment
Issue No. : #906
Code Stack : 
Close #906
1.Alignment issue of the text and links.
2. Icons where displaying twice.
3. Google translator script working .
4. Hovering effect to icons according to there logo.
5. Made the page responsive too.
Before:
After:
https://github.com/apu52/Travel_Website/assets/168854094/97798ac0-2679-4b09-817f-c3143a7dce50
Also made is responsive for small screen:
> fix: Footer Section alignment issue fixed

- faq.html
Fixed issue: #1004 
Title : #1004
Issue No. : #1004
Code Stack : JavaScript
Close #1004 
- Modify the "Send Email" button to open the user's default email client with the recipient's email address pre-filled.
- This update will enhance user experience by allowing users to easily send an email without manually entering the recipient's address.
https://github.com/apu52/Travel_Website/assets/159511364/66279875-2bd1-44ab-9ed1-64c58182401f
> feat: Update "Send Email" Button to Open Default Email Client

- faq.html
Fixed issue: #1000
Title : #1000
Issue No. : #1000
Close #1000 
- Resolve the issue where the links in the navbar on the FAQ page are not navigating to the respective pages as intended.
- Update the href attributes to ensure correct paths and functionality for all navbar links.
- Test the links to verify that each one correctly navigates to the intended section or page.
https://github.com/apu52/Travel_Website/assets/159511364/fa5aaff2-d90c-4a3c-ac71-a579464afa0e
> fix: Navbar Links on FAQ Page

- story.html
- styles.css
Title : Footer Content Alignment and Responsiveness fixed 
Issue No. : #1020 
Close #1020 
The footer content has been aligned properly and has been made responsive as  the footer contents used to be displayed unorderly especially during mobile view. This has been solved.
> fix: fixed footer content alignment

- .github/workflows/label-issues.yaml
Title : Automatically add label to issues
Issue No. : #952 
Close #952 
When a user creates a new issue,
based on the user selecting "I'm a GSSOC'24 contributor" or "I'm a VSOC'24 contributor" ,
automatically "gssoc" or "VSoC'24" label is added respectively .
This contribution is under GSSOC'24
> feat: Automatically add label to issues

- styles.css
- thankyou.css
- trending.css
Title: Enhancement: Improved Styling for Thank You Page, Navbar, and Trending Tour Card Alignment
Issue No.: #1063
Code Stack: HTML, CSS, JavaScript
Close #1063
Enhanced the visual appeal and user experience of the travel website by updating the styling for the Thank You Page, Navbar, and Trending Tour Card alignment. Details include:
- Updated Thank You Page with enhanced color scheme and typography .
- # Description
Enhanced the visual appeal and user experience of the travel website's Thank You Page by implementing the following stylistic improvements:
- **Color Scheme Enhancement**: Updated the color scheme to incorporate soothing tones that align with the travel theme, enhancing visual coherence and brand identity.
- **Typography Improvement**: Refined typography choices for improved …
> feat: Updated navbar colors and fixed alignment issues

- index.html
Title : Fixed the email input box style issue of contact us section.
Issue No. : #1060 
Close #1060 
- Fixed the email input box style issue of contact us section.
- Now, all the 3 input boxes have same style.
yes GSSoC'24
> fix: the email input box style issue of contact us section.

- faq.html
Title : No effect of the dark mode on the FAQ page .
Issue No. : #1022
Code Stack : CSS,HTML,JavaScript
Close #1022
I have added dark mode effects on the FAQ page similar to other pages .
I have made the dark mode effects similar to the home page , for instance the buttons on the navbar .
Yes GSSoC'24.
> feat: Added dark mode effects on the FAQ page.

- index.html
- styles.css
Title : Improved navigation links for mobile
Issue No. : #1090
Code Stack : 
Close #1090
I made the site's navigation bar responsive for different width of mobile devices. If the device with is small, I moved the buttons from navigation bar to the Hamburger Menu. Firstly the signup/login button moves to the menu, and then the view button. The hyperlinks work there as well. Finally if the screen width is too small(350px) the logo name is removed making space for the other more required items in the navigation
Before:
https://github.com/user-attachments/assets/5fe9adaf-62e9-40aa-99f2-ad8e9b49548c
After:
https://github.com/user-attachments/assets/80e4a23c-ac2a-49b4-82a3-52381911a3ff
> feat: Improved navLinks for mobile

- Licensing.html
- index.html
Hey @apu52 and @itsekta
Issue closes #1031 
Here's what I did -
-    Added a Dedicated Licensing Page
-    Added styling to it so that it will follow the color theme of website
-    I also added a "back to home" button
-    I Added the navigating link in the footer
******Video/Screenshot:******
****Please take a look and review it****
> feat: 🌟Added "Licensing page" reflecting "MIT License"

- Image-Gallery/style.css
- styles.css
Title : Google logo Adjustment
Issue No. : #1085
Close #1085
Made the changes to the google logo as it was not visible for good user experience.
BEFORE:
AFTER:
> feat: Google logo Adjustment

- index.html
- styles.css
Title : Improved CSS code in the hotel booking section
Issue No. : #1117
Code Stack : 
Close #1117 
Improved the CSS, by using CSS flexbox, and removed the unnecessary \<br> elements.
Before Changes:
After changes:
> fix: Improved CSS

- hotel.html
Title : improve ui of book hotel form
Issue No. : #1110 
Code Stack : 
Close #1110  
https://github.com/user-attachments/assets/7c879314-5d36-4cab-b517-fefe6fc415dd
> feat: enhance book hotel form

- styles.css
Title :Subscribe option is not visible clearly .
Issue No. : #1083
Close #1083
Text subscribe is now clearly visible in the button above the footer .
GSSOC
> fix: Subscribe text is now clearly visible.

- login/login.css
- login/script.js
- newLogin.html
Title :add popup for successful login and register
Issue No. :#1109
Code Stack : html css and js 
Close #1109 
add a messge successful login and succeessful register in login page 
https://github.com/user-attachments/assets/7fa4d021-c908-40ab-87b1-cce12de4d633
> feat: add popup for successful login and register

- feed.html
- feed.js
- Added client-side validation for feedback form fields:
- Required fields for name, email, and feedback comments
- Minimum length check for feedback comments (minimum 4 characters)
- Restriction on future dates for event date selection
- Implemented reset functionality for star ratings after form submission
This change improves user experience by enforcing required fields and ensuring data integrity in the feedback form.
Title : [Bug]: Tour Feebdback form submits without filling any information
Issue No. : #1171 
Code Stack :  HTML, JavaScript
Close #1171 
- Added client-side validation for feedback form fields:
- Required fields for name, email, and feedback comments
- Minimum length check for feedback comments (minimum 4 characters)
- Restriction on future dates for event date …
> fix: Tour Feebdback form submits without filling any information #1171

- index.html
Hey  @apu52 
- issue closes #1205 
I have hidden the cursor trail effect in the mobile view
https://github.com/user-attachments/assets/23bc50b4-13b4-4067-8489-d13e20bae3f7
> feat: Hide the Cursor Trail Effect in Mobile view

- Cultural_Exp.html
Title :
Issue No. : #1192
Code Stack : HTML CSS JS
Close #1192
- alignment fixed
- searchbar added
- filters added
- respective js added
- icons added to each trip card
> feat: Improved UI of Cultural_Exp.html

- README.md
Title :  Improve Landing Page Visuals in README.md
Issue No. : #1096
Close #1096
> feat: Improved Landing Page Visuals in README.md

- Image-Gallery/style.css
Title : book Now Button
Issue No. : #1222
Code Stack : 
Close #1222
> feat: Book now button 

- contributors.css
- contributors.html
- index.html
Title : Contributors Update
Issue No. : #1201
Code Stack : 
Improved UI of contributors page.
Linked with the main page of website.
Made the page responsive
https://github.com/user-attachments/assets/b8cf3870-f979-448d-8561-9384cf945f11
https://github.com/user-attachments/assets/1a829432-85a4-4d23-9cb6-58aa420cb216
> feat: Contributors Update

- faq-website.css
- index.html
- styles.css
Title : Navbar Improvements
Issue No. :  #1231 
Close #1231 
- Navbar Improvements
- Vanilla JS sticky 
- on scroll navbar gradient background added
- on scroll the the navbar is scaled to float on screen
- On hover effects modified to match overall theme of the website
> feat: Navbar Improvements

- README.md
Title : Enhance License and Acknowledgments Section Clarity
Issue No. : #1095
Close #1095
> feat: Enhance License and Acknowledgments Section and Project mentor section

- blog.html
Title : Added Popular Categories with full logic
Issue No. : #1251
Code Stack : js
Close #1251
- **Display Top 5 Categories**: Ranks and shows the top 5 categories based on their frequency.
- **Category Filtering**: Clicking on a category filters blog posts to only show those with the selected category.
- **Dynamic Category List**: Updates the category list dynamically based on the blog posts data.
https://www.awesomescreenshot.com/video/29994250?key=219b315397adef7a03fc3ab374a86f8a
> feat: Added Popular Categories with full logic

- .vscode/settings.json
- index.html
Title : Chatbot enhancement
Issue No. : #1059 
Code Stack :  JS
Close #1059
Created a chatbot that is not only able to answer about reservation queries but can also answer queries regarding tourist places, stay, etc.  It provides users to choose whether they have a general query or a reservation related query.
https://github.com/user-attachments/assets/70702087-b770-4c35-9f28-052fb657caf5
I have have added the feature such that the chatbot works on user intent. Also i have added the knowledge base such that it answers the queries using both knowledge base and AI.
> feat: Chatbot enhancement #1059

- footer.css
- index.html
- styles.css
Title : Updating language selection UI to make it more appropriate
Issue No. : #1257 
Code Stack :  HTML, CSS
Close #1257 
Updated previous Select language UI, to make it more suitable with site's Design
new UI
> feat: Select language ui updated

- contributors.html
- contributors.js
Title : Added pagination feature in contributors page.
Issue No. : #1298 
Code Stack :  HTML, CSS, JavaScript
Close #1298 
- Added pagination feature in contributors page.
- Now user can view all the contributors using pagination feature.
https://github.com/user-attachments/assets/53290f0b-c3b9-4bc4-bb4c-86c916eafd63
_Please review & merge my pull-request under GSSoC'24_
Yes, GSSoC'24
> feat: Added pagination feature in contributors page

- index.html
- packages.html
Title : added the packages page
Issue No. : #1297
Close #1297
- added a packages page
- added the navbar in it
- added trips, hotel and pricing sections
- added a video background with a proper overlay
- added few fade and hover effects
https://www.awesomescreenshot.com/video/30174347?key=af98b0f456970bdcc93d9e643a9e9e02
- [x I have gone through the  `contributing.md` file before contributing
> feat: added the packages page

- contributors.css
- contributors.html
Hey @apu52  @itsekta 
issue closes #1305 
- I have **added the Diagonal Effect on Hovering** on each contributors card
- Also **Added Transitional Text Shadows to the `Contributors-name` and `Github-Contributions` info**
- **Added "Img Border" On hover** to make focus on it.
- **Followed the website theme for it.**
- **It Works in both Dark and Light Mode** Very Well !
- **Changed the "Background"** of the Page to Effective One.
Please take a look - 
https://github.com/user-attachments/assets/4e5c3530-7540-47b7-a7b2-a17fb5513320
thankyou!
> feat: ✔️Added Diagonal-Hovering Effect to Each Card! 

- package.css
- packages.html
Title  Navbar not visible #1311 
Issue No. :#1311
Code Stack : 
- [X ] Feature enhancement
> feat: Navbar Not Visible in Packages #1311

- Adventure.html
- Cultural_Exp.html
- HoneyMoon.html
- contributors.html
- privacy.html
- tnc.css
- tnc.html
Hey @itsekta @apu52 
issue closes #1306 
I have **added the progress scrollbar in all the pages** in which it was absent.
**please take a look -**
https://github.com/user-attachments/assets/5e6de4c2-3c4c-4d7b-a75f-464828019954
Please review it 
Thankyou !
> feat: ✔️ Added "ProgressBar" in All the Absent Pages! 

- payment.css
- payment.html
Title : Improved Checkout page
Issue No. : #1338 
Code Stack : HTML,CSS,JS
Close #1338
- Changed the UI of guide section
- Changed the navbar
- Added checkout option after cart reckeck
- Added place your order button
- Also added dark mode features
- changed placeholders for some option
- added calender icon and MM/YY option for credit card 
- Now when checkout is clicked, the page scrolls down and opens hidden payment options
> feat: Payment page improved

- newLogin.css
- newLogin.html
Title : Add button to redirect to home page from the login/signup page.
Issue No. : #1336 
Code Stack : 
Close #1336 
Resolved Bug 'No link/button to redirect to home page from the login/signup page'. Added a new button to redirect to home page.
> fix: #1336 Add redirect button to home-page.

- Adventure.html
- Cultural_Exp.html
- faq.html
- index.html
Hey @apu52 
- issue closes #1344 
I have added the favicon to the all pages
> feat: Added Favicon to All Pages

- index.html
Title :  Fixed img file path testimonial
Issue No. : #1494 
Code Stack : 
> chore: fixed img file path

- styles.css
Title : Fix navbar size and remove red line from navlink section
Issue No. : 1486
Close #1486
1.Improved the layout and styling of the navigation bar to ensure all elements are visible and properly aligned. Specifically, I made the following changes:
*Adjusted the styles for .nav-container to set its width to 100%, display as flex, and position as fixed, ensuring it takes up the full width of the screen.
*Fixed the size of the navigation elements, making sure the view button is now clearly visible.
*Refactored the CSS styles for .navLinks to improve its layout and positioning, ensuring it is properly aligned with other navigation elements.
"Previously, the navigation bar had layout issues, and the view button was not visible. After these changes, the navigation bar is now …
> fix: The size of the navbar seems off, and the red line that appears when we click doesn’t quite fit the design. #1486

- topdeals/topdeals.html
Issue No. :1426
Close #1426
included the nav bar in the top deals page
Before adding the nav bar
After adding the nav bar
> fix: no nav bar in top deals , issue #1426

- 404.html
- HoneyMoon.html
- Licensing.html
- Signup.html
- about.html
- contributors.html
- newLogin.html
- packages.html
- thankyou.html
- tnc.html
- topdeals/topdeals.html
Title : Fevicon not visible on all html pages 
Issue No. : 1431 
Close #1431 
Added missing favicon to html pages below:
1. 404
2. about
3. contributors
4. HoneyMoon
5. Licensing
6. newLogin
7. packages
8. Signup
9. thankyou
10. tnc
11. topdeal
**(AND OTHERS)**
> fix: Fevicon not visible on all html pages #1431

- index.html
Title :The scroll-back button directly jumps to the top; it does not scroll smoothly to the top. 
Issue No. : #1455 
Now go to top button is scrolling smoothly instead of jumping to the top
Before:
[before.webm](https://github.com/user-attachments/assets/66c111a1-ac73-4cb4-9770-d7dc93fbbd42)
After:
[after.webm](https://github.com/user-attachments/assets/c73e4cbd-6c5a-4a3f-9d8e-c88ffcf629fd)
> fix: Scroll back button smoothly scrolling issue

- index.html
Title : valid Email while Subscribing
Issue No. : #1547 
Code Stack : html, JavaScript 
Close #1547 
improve the regex to ensure the domain part is properly validated (e.g., at least two characters after the dot).
Added an email validation regex (email Pattern) to check the input format.
If the email is valid, the success message is displayed.
If the email is invalid, an error message is displayed for 4 seconds.
https://github.com/user-attachments/assets/313757b3-5674-4068-b16a-e7f806f403f8
> fix: Add valid email checker while subscribing

- index.html
Title : Resolved the issue of the hamburger
Issue No. : #1518 
Close #1512 
https://github.com/user-attachments/assets/36113849-fbb1-486f-b51e-9f1b1115438f
> feat: Resolved the issue of the hamburger #1582

- dedicated destinations/Ladakh/ladakh.css
- dedicated destinations/Ladakh/ladakh.html
- dedicated destinations/Ladakh/ladakh.js
- dedicated destinations/Taj_Mahal/Taj.css
- dedicated destinations/Taj_Mahal/Taj.html
- dedicated destinations/Taj_Mahal/Taj.js
- dedicated destinations/thailand/t.css
- dedicated destinations/thailand/t.html
- dedicated destinations/thailand/t.js
Added weather widget 
Issue No. : #1640 
Code Stack :  HTML, CSS, JavaScript
- Implemented a responsive and visually appealing weather widget.
- Enhanced UI to highlight weather details with color-coded headings and data.
- Integrated API for fetching live weather data with extended features like snow details, wind speed, and pressure.
https://github.com/user-attachments/assets/7eaa03df-131d-4549-870f-1bc38bceec1b
- The widget dynamically adjusts to the screen size and enhances the user experience with animations.
- Implemented a fallback mechanism for API errors to show default data.
> feat: added weather widget

- mapa.html
Title : View button lead to blank page
Issue No. : #1641
Code Stack : HTML and JS
Close #1641
As Live google map API is not free instead of using it for time being and look of website i suggest using Leaflet.js which provides basic map we can statically add the locations of the places in this Leaflet.js based code
> fix: View button lead to blank page

- mapa.html
Title : Added more locations in view page
Issue No. : #1653
Code Stack : HTML CSS JS
Close #1653
Added more locations in view page
- [X ] I have commented my code, particularly in hard-to-understand areas.
> feat: Added more locations in view page

- index.html
Title : navbar changes 
Issue No. : #1654
Code Stack : HTML CSS JS
Close #1654
fixed the spacing issue in home navbar
https://github.com/user-attachments/assets/bb830ea3-8018-4e15-9855-77cd05d675de
> fix: fixed spacing issue in navbar #1654

- feed.css
- feed.html
Title : Twitter logo update at feed.html page
Issue No. : #1647 
Code Stack : HTML , CSS
Close #1647 
Update the twitter logo at feed.html page
https://github.com/user-attachments/assets/50a36a33-07d0-417a-9324-13e3dd04ccdc
> fix: In feed.html page twitter logo update

- styles.css
Title : Subscribe Button Appearance is Disruptive #1672
Issue No. : #1672
Close #1672
This PR improves the styling and functionality of the subscribe button in the Subscribe section. The changes ensure proper alignment, responsiveness, and enhanced hover effects for a better user experience.
> fix: Fixed Subscribe Button Alignment and Styling in Subscribe Section

- counter.css
- index.html
Title : Improve the UI of the mentioned sections to improve user readability. #1660
Issue No. :  #1660
Close #1660 
added padding around the text below the images to ensure better separation and readability and made it responsive.
> fix: Improve the UI of the mentioned sections to improve user readability

- explore.css
Added Padding #1707 
Title : Added padding to sub titles
Issue No. : #1707 
Close #1707 
Fixed the padding issue to improve subtitle visibility.
> fix: Text Visibility Issue Due to Insufficient Padding
